/**
 * Seed script for Minarets of Cairo
 * Run: npx tsx server/seed.ts
 */
import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import {
  periods,
  districts,
  placeTypes,
  places,
  sources,
  walks,
  comparisons,
  detectiveActivities,
  stories,
} from "../drizzle/schema";

async function seed() {
  const connection = await mysql.createConnection(process.env.DATABASE_URL!);
  const db = drizzle(connection);
  console.log("🌱 Seeding Minarets of Cairo database...");

  // PERIODS
  console.log("  → Seeding periods...");
  await db.insert(periods).ignore().values([
    { slug: "rashidun-umayyad", nameEn: "Rashidun & Umayyad Foundations", nameAr: "الفتح الإسلامي والأمويون", startYear: 641, endYear: 750, descriptionEn: "The Arab conquest of Egypt in 641 CE established Fustat as the first Islamic capital.", descriptionAr: "أسس الفتح العربي لمصر عام ٦٤١م مدينة الفسطاط أولى العواصم الإسلامية.", colorToken: "period-rashidun", sortOrder: 1 },
    { slug: "abbasid", nameEn: "Abbasid Administration", nameAr: "الإدارة العباسية", startYear: 750, endYear: 868, descriptionEn: "Under Abbasid rule, Egypt was governed by appointed governors. The Nilometer exemplifies Abbasid scientific achievement.", descriptionAr: "في عهد العباسيين حُكمت مصر بولاة معيّنين. يجسّد مقياس النيل الإنجاز العلمي العباسي.", colorToken: "period-abbasid", sortOrder: 2 },
    { slug: "tulunid", nameEn: "Tulunid Cairo", nameAr: "القاهرة الطولونية", startYear: 868, endYear: 905, descriptionEn: "Ahmad Ibn Tulun established al-Qata'i as a new capital. His great mosque remains one of Cairo's most important early Islamic monuments.", descriptionAr: "أسس أحمد بن طولون مدينة القطائع عاصمة جديدة. لا يزال جامعه أحد أهم المعالم الإسلامية المبكرة في القاهرة.", colorToken: "period-tulunid", sortOrder: 3 },
    { slug: "fatimid", nameEn: "Fatimid Cairo", nameAr: "القاهرة الفاطمية", startYear: 969, endYear: 1171, descriptionEn: "The Fatimid caliphate founded al-Qahira in 969 CE. Their rule produced al-Azhar, the great northern gates, and al-Muizz Street.", descriptionAr: "أسست الخلافة الفاطمية مدينة القاهرة عام ٩٦٩م. أنتج حكمهم الأزهر والبوابات الشمالية الكبرى وشارع المعز.", colorToken: "period-fatimid", sortOrder: 4 },
    { slug: "ayyubid", nameEn: "Ayyubid Cairo", nameAr: "القاهرة الأيوبية", startYear: 1171, endYear: 1250, descriptionEn: "Salah al-Din ended Fatimid rule and built the Citadel, expanding Sunni institutions.", descriptionAr: "أنهى صلاح الدين الحكم الفاطمي وبنى القلعة ووسّع المؤسسات السنية.", colorToken: "period-ayyubid", sortOrder: 5 },
    { slug: "mamluk-bahri", nameEn: "Bahri Mamluk Cairo", nameAr: "القاهرة المملوكية البحرية", startYear: 1250, endYear: 1382, descriptionEn: "The Bahri Mamluks transformed Cairo into one of the Islamic world's greatest cities.", descriptionAr: "حوّل المماليك البحرية القاهرة إلى إحدى أعظم مدن العالم الإسلامي.", colorToken: "period-mamluk-bahri", sortOrder: 6 },
    { slug: "mamluk-burji", nameEn: "Burji Mamluk Cairo", nameAr: "القاهرة المملوكية البرجية", startYear: 1382, endYear: 1517, descriptionEn: "The Burji Mamluks continued grand patronage. Carved stone domes reached their peak of refinement.", descriptionAr: "واصل المماليك البرجية تقليد الرعاية الكبرى. بلغت القباب الحجرية المنحوتة ذروة رقيّها.", colorToken: "period-mamluk-burji", sortOrder: 7 },
    { slug: "ottoman-early", nameEn: "Early Ottoman Cairo", nameAr: "القاهرة العثمانية المبكرة", startYear: 1517, endYear: 1650, descriptionEn: "The Ottoman conquest brought central domes, pencil minarets, and Iznik tiles.", descriptionAr: "أحضر الفتح العثماني قباباً مركزية ومآذن قلمية وبلاط إزنيق.", colorToken: "period-ottoman-early", sortOrder: 8 },
    { slug: "ottoman-late", nameEn: "Late Ottoman Cairo", nameAr: "القاهرة العثمانية المتأخرة", startYear: 1650, endYear: 1798, descriptionEn: "The late Ottoman period saw the rise of powerful Mamluk beys who commissioned sabils, kuttabs, and mosques.", descriptionAr: "شهدت الحقبة العثمانية المتأخرة صعود أمراء المماليك الأقوياء الذين أنشأوا السبل والكتاتيب والمساجد.", colorToken: "period-ottoman-late", sortOrder: 9 },
    { slug: "muhammad-ali", nameEn: "Muhammad Ali Dynasty", nameAr: "أسرة محمد علي", startYear: 1805, endYear: 1952, descriptionEn: "Muhammad Ali modernized Egypt and transformed the Citadel skyline with his great mosque.", descriptionAr: "حدّث محمد علي مصر وغيّر أفق القلعة بجامعه العظيم.", colorToken: "period-muhammad-ali", sortOrder: 10 },
    { slug: "modern", nameEn: "Modern Conservation & Living Heritage", nameAr: "الصون الحديث والتراث الحي", startYear: 1952, endYear: 2025, descriptionEn: "UNESCO listing, the Aga Khan Trust for Culture, and Egyptian heritage bodies work to conserve Historic Cairo.", descriptionAr: "تعمل قوائم اليونسكو وصندوق الآغا خان للثقافة والهيئات المصرية على صون القاهرة التاريخية.", colorToken: "period-modern", sortOrder: 11 },
  ]);

  // DISTRICTS
  console.log("  → Seeding districts...");
  await db.insert(districts).ignore().values([
    { slug: "fustat", nameEn: "Fustat", nameAr: "الفسطاط", descriptionEn: "The first Islamic capital of Egypt, founded 641 CE.", descriptionAr: "أولى عواصم مصر الإسلامية، تأسست عام ٦٤١م.", lat: "30.0050000", lng: "31.2300000" },
    { slug: "al-muizz", nameEn: "Al-Muizz Street & Bayn al-Qasrayn", nameAr: "شارع المعز وبين القصرين", descriptionEn: "The historic spine of Fatimid Cairo, lined with monuments from ten centuries.", descriptionAr: "العمود الفقري التاريخي للقاهرة الفاطمية.", lat: "30.0500000", lng: "31.2620000" },
    { slug: "darb-al-ahmar", nameEn: "Darb al-Ahmar", nameAr: "الدرب الأحمر", descriptionEn: "A living historic district east of al-Muizz.", descriptionAr: "حي تاريخي حي شرق شارع المعز.", lat: "30.0430000", lng: "31.2640000" },
    { slug: "citadel", nameEn: "The Citadel", nameAr: "القلعة", descriptionEn: "The fortified seat of power above Cairo.", descriptionAr: "مقر السلطة المحصّن فوق القاهرة.", lat: "30.0287000", lng: "31.2597000" },
    { slug: "northern-cemetery", nameEn: "Northern Cemetery", nameAr: "القرافة الشمالية", descriptionEn: "A vast funerary landscape containing major Mamluk mausoleums.", descriptionAr: "مشهد جنائزي شاسع يضم أضرحة مملوكية كبرى.", lat: "30.0530000", lng: "31.2780000" },
    { slug: "al-azhar-hussein", nameEn: "Al-Azhar & Al-Hussein", nameAr: "الأزهر والحسين", descriptionEn: "The religious and commercial heart of Islamic Cairo.", descriptionAr: "القلب الديني والتجاري للقاهرة الإسلامية.", lat: "30.0460000", lng: "31.2630000" },
    { slug: "al-saliba", nameEn: "Al-Saliba & Ibn Tulun", nameAr: "الصليبة وابن طولون", descriptionEn: "The neighborhood around Ibn Tulun Mosque.", descriptionAr: "الحي المحيط بجامع ابن طولون.", lat: "30.0370000", lng: "31.2490000" },
    { slug: "roda-island", nameEn: "Roda Island", nameAr: "جزيرة الروضة", descriptionEn: "An island in the Nile containing the Nilometer.", descriptionAr: "جزيرة في النيل تضم مقياس النيل.", lat: "30.0100000", lng: "31.2250000" },
  ]);

  // PLACE TYPES
  console.log("  → Seeding place types...");
  await db.insert(placeTypes).ignore().values([
    { slug: "mosque", nameEn: "Mosque", nameAr: "مسجد", icon: "mosque" },
    { slug: "madrasa", nameEn: "Madrasa", nameAr: "مدرسة", icon: "school" },
    { slug: "mausoleum", nameEn: "Mausoleum", nameAr: "ضريح", icon: "landmark" },
    { slug: "complex", nameEn: "Complex", nameAr: "مجمع", icon: "building" },
    { slug: "gate", nameEn: "Gate", nameAr: "باب", icon: "door-open" },
    { slug: "citadel-type", nameEn: "Citadel / Fortification", nameAr: "قلعة / تحصين", icon: "shield" },
    { slug: "palace", nameEn: "Palace", nameAr: "قصر", icon: "castle" },
    { slug: "house", nameEn: "Historic House", nameAr: "بيت تاريخي", icon: "home" },
    { slug: "sabil", nameEn: "Sabil-Kuttab", nameAr: "سبيل وكتاب", icon: "droplets" },
    { slug: "khanqah", nameEn: "Khanqah", nameAr: "خانقاه", icon: "star" },
    { slug: "museum", nameEn: "Museum", nameAr: "متحف", icon: "museum" },
    { slug: "street", nameEn: "Street / Urban Area", nameAr: "شارع / منطقة حضرية", icon: "map-pin" },
    { slug: "cemetery", nameEn: "Cemetery", nameAr: "مقبرة", icon: "leaf" },
    { slug: "nilometer", nameEn: "Nilometer", nameAr: "مقياس النيل", icon: "ruler" },
    { slug: "park", nameEn: "Park / Garden", nameAr: "حديقة", icon: "tree" },
    { slug: "market", nameEn: "Market / Khan", nameAr: "سوق / خان", icon: "store" },
    { slug: "shrine", nameEn: "Shrine", nameAr: "مقام", icon: "heart" },
  ]);

  // SOURCES
  console.log("  → Seeding sources...");
  await db.insert(sources).ignore().values([
    { slug: "unesco-historic-cairo", titleEn: "UNESCO World Heritage: Historic Cairo", titleAr: "اليونسكو: القاهرة التاريخية", url: "https://whc.unesco.org/en/list/89", sourceType: "institution", year: 1979 },
    { slug: "behrens-abouseif-1989", titleEn: "Islamic Architecture in Cairo: An Introduction", titleAr: "العمارة الإسلامية في القاهرة: مقدمة", authors: "Doris Behrens-Abouseif", publisher: "Brill", year: 1989, sourceType: "academic" },
    { slug: "williams-2008", titleEn: "Islamic Monuments in Cairo: The Practical Guide", titleAr: "المعالم الإسلامية في القاهرة: الدليل العملي", authors: "Caroline Williams", publisher: "American University in Cairo Press", year: 2008, sourceType: "academic" },
    { slug: "aga-khan-trust", titleEn: "Aga Khan Trust for Culture: Historic Cairo", titleAr: "صندوق الآغا خان للثقافة: القاهرة التاريخية", url: "https://www.akdn.org/architecture/project/historic-cairo", sourceType: "conservation", year: 2005 },
    { slug: "mia-cairo", titleEn: "Museum of Islamic Art, Cairo", titleAr: "متحف الفن الإسلامي، القاهرة", url: "https://mia.gov.eg", sourceType: "museum" },
    { slug: "creswell-1952", titleEn: "The Muslim Architecture of Egypt", titleAr: "العمارة الإسلامية في مصر", authors: "K.A.C. Creswell", publisher: "Clarendon Press", year: 1952, sourceType: "academic" },
  ]);

  // PLACES
  console.log("  → Seeding 22 places...");
  const placesData = [
    { slug: "mosque-amr-ibn-al-as", nameEn: "Mosque of Amr ibn al-As", nameAr: "جامع عمرو بن العاص", periodId: 1, districtId: 1, placeTypeId: 1, foundedYear: 641, dateCertainty: "certain" as const, dateDisplayEn: "Founded 641–642 CE; repeatedly rebuilt", dateDisplayAr: "تأسس ٦٤١–٦٤٢م؛ أُعيد بناؤه مراراً", patronEn: "Amr ibn al-As", patronAr: "عمرو بن العاص", originalFunctionEn: "Congregational mosque", originalFunctionAr: "جامع", currentFunctionEn: "Active mosque", currentFunctionAr: "مسجد نشط", briefEn: "Founded in Fustat after the Arab conquest of Egypt in 641 CE, this is traditionally regarded as the first mosque established in Egypt and Africa. Almost none of the original seventh-century fabric survives — the building has been enlarged and rebuilt many times over fourteen centuries. Its story is one of continuity, repeated renewal, and the growth of the earliest Islamic capital rather than a preserved ancient structure. The vast courtyard and arcades reflect later reconstructions. Visitors should understand they are experiencing a living religious site shaped by many generations, not a preserved seventh-century monument.", briefAr: "تأسس في الفسطاط عقب الفتح العربي لمصر عام ٦٤١م، ويُعدّ تقليدياً أول مسجد أُقيم في مصر وأفريقيا. لا يكاد يبقى شيء من نسيجه الأصلي في القرن السابع، إذ وُسّع المبنى وأُعيد بناؤه مرات عديدة على مدى أربعة عشر قرناً. قصته قصة استمرارية وتجديد متكرر ونمو للعاصمة الإسلامية الأولى لا قصة بنية محفوظة.", clarificationEn: "The current building is not a seventh-century structure. It has been rebuilt so many times that no original fabric remains.", clarificationAr: "المبنى الحالي ليس من القرن السابع. أُعيد بناؤه مرات عديدة حتى لم يبق من نسيجه الأصلي شيء.", keyDates: [{ year: 641, labelEn: "Foundation by Amr ibn al-As", labelAr: "التأسيس بيد عمرو بن العاص" }], lat: "30.0053000", lng: "31.2310000", activeWorship: true, ticketed: false, photographyAllowed: "exterior_only" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Courtyard scale, arcades, Fustat context", priorityVisualStoryAr: "مقياس الفناء والأروقة وسياق الفسطاط", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mosque_of_Amr_ibn_al-As_from_outside.jpg/800px-Mosque_of_Amr_ibn_al-As_from_outside.jpg", coverImageAlt: "Exterior of the Mosque of Amr ibn al-As in Fustat, Cairo", coverImageAltAr: "واجهة جامع عمرو بن العاص في الفسطاط بالقاهرة", coverImageAttribution: "Wikimedia Commons / Public Domain", coverImageLicense: "Public Domain" },
    { slug: "nilometer-roda", nameEn: "Nilometer on Roda Island", nameAr: "مقياس النيل بالروضة", periodId: 2, districtId: 8, placeTypeId: 14, foundedYear: 861, dateCertainty: "certain" as const, dateDisplayEn: "861 CE (Abbasid period)", dateDisplayAr: "٨٦١م (العصر العباسي)", patronEn: "Commissioned under Abbasid Caliph al-Mutawakkil", patronAr: "بُني في عهد الخليفة العباسي المتوكل", originalFunctionEn: "Measurement of Nile flood levels for taxation and agriculture", originalFunctionAr: "قياس منسوب فيضان النيل للضرائب والزراعة", currentFunctionEn: "Historic monument and museum", currentFunctionAr: "معلم تاريخي ومتحف", briefEn: "Commissioned in the Abbasid period to measure the annual Nile flood, the Nilometer on Roda Island linked water level, taxation, agriculture, and the life of the city. Its octagonal marble column, descending stair, geometric chamber, and Kufic inscriptions make it one of Egypt's most precise surviving early Islamic structures. The flood level determined tax rates and predicted famine or abundance — making this an instrument of governance as much as science.", briefAr: "بُني في العصر العباسي لقياس فيضان النيل السنوي، وربط مقياس النيل في جزيرة الروضة منسوب المياه بالضرائب والزراعة وحياة المدينة. يجعله عموده الرخامي المثمن ودرجه المنحدر وحجرته الهندسية وكتاباته الكوفية أحد أدق المنشآت الإسلامية المبكرة الباقية في مصر.", keyDates: [{ year: 861, labelEn: "Construction under al-Mutawakkil", labelAr: "البناء في عهد المتوكل" }], lat: "30.0098000", lng: "31.2231000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 45, priorityVisualStoryEn: "Measuring column, descending stair, inscriptions", priorityVisualStoryAr: "عمود القياس والدرج المنحدر والكتابات", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Nilometer_on_Rhoda_Island.jpg/800px-Nilometer_on_Rhoda_Island.jpg", coverImageAlt: "The Nilometer column on Roda Island, Cairo", coverImageAltAr: "عمود مقياس النيل في جزيرة الروضة بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "mosque-ibn-tulun", nameEn: "Mosque of Ahmad Ibn Tulun", nameAr: "جامع أحمد بن طولون", periodId: 3, districtId: 7, placeTypeId: 1, foundedYear: 876, foundedYearEnd: 879, dateCertainty: "certain" as const, dateDisplayEn: "876–879 CE", dateDisplayAr: "٨٧٦–٨٧٩م", patronEn: "Ahmad Ibn Tulun", patronAr: "أحمد بن طولون", originalFunctionEn: "Congregational mosque of al-Qata'i capital", originalFunctionAr: "جامع عاصمة القطائع", currentFunctionEn: "Active mosque and historic monument", currentFunctionAr: "مسجد نشط ومعلم تاريخي", briefEn: "Built for Ahmad Ibn Tulun's new capital al-Qata'i, this mosque is one of Cairo's most important surviving early Islamic buildings. Its vast courtyard, brick construction with stucco ornament, rhythmic arcades, and famous spiral-form minaret connect Cairo to Abbasid architectural traditions while expressing Tulunid independence. The minaret's external spiral stair is unique in Egypt and echoes the great mosque at Samarra in Iraq. The mosque's scale — accommodating an entire army — and its state of preservation make it an essential starting point for understanding Islamic Cairo.", briefAr: "بُني لعاصمة أحمد بن طولون الجديدة القطائع، ويُعدّ هذا الجامع أحد أهم المباني الإسلامية المبكرة الباقية في القاهرة. يربط فناؤه الشاسع وبناؤه الطوبي بزخارف الجص وأروقته المتناسقة ومئذنته الحلزونية الشهيرة القاهرةَ بالتقاليد المعمارية العباسية مع التعبير عن الاستقلالية الطولونية.", keyDates: [{ year: 876, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 879, labelEn: "Mosque completed", labelAr: "اكتمال الجامع" }, { year: 1296, labelEn: "Major restoration by Lajin", labelAr: "ترميم كبير بيد لاجين" }], lat: "30.0374000", lng: "31.2490000", activeWorship: true, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 45, recommendedDurationMax: 90, priorityVisualStoryEn: "Vast courtyard, spiral minaret, stucco ornament", priorityVisualStoryAr: "الفناء الشاسع والمئذنة الحلزونية وزخارف الجص", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Ibn_Tulun_Mosque_-_Cairo%2C_Egypt.jpg/800px-Ibn_Tulun_Mosque_-_Cairo%2C_Egypt.jpg", coverImageAlt: "The courtyard and spiral minaret of Ibn Tulun Mosque, Cairo", coverImageAltAr: "فناء جامع ابن طولون ومئذنته الحلزونية بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-azhar-mosque", nameEn: "Al-Azhar Mosque", nameAr: "الجامع الأزهر", periodId: 4, districtId: 6, placeTypeId: 1, foundedYear: 970, foundedYearEnd: 972, dateCertainty: "certain" as const, dateDisplayEn: "Founded 970–972 CE; major additions through the 18th century", dateDisplayAr: "تأسس ٩٧٠–٩٧٢م؛ إضافات كبرى حتى القرن الثامن عشر", patronEn: "Jawhar al-Siqilli, general of Caliph al-Mu'izz", patronAr: "جوهر الصقلي، قائد الخليفة المعز", originalFunctionEn: "Fatimid congregational mosque and center of learning", originalFunctionAr: "جامع فاطمي ومركز للتعلم", currentFunctionEn: "Active mosque and seat of Al-Azhar University", currentFunctionAr: "مسجد نشط ومقر جامعة الأزهر", briefEn: "Established soon after the Fatimid foundation of Cairo, al-Azhar developed from a congregational mosque into one of the Islamic world's most influential centers of learning. Its present architecture records many later dynasties — Fatimid, Ayyubid, Mamluk, and Ottoman additions are all visible in its layered minarets, courtyard, and teaching spaces. The mosque is an active place of worship and a functioning university, making it a monument of living institutional history rather than a frozen medieval structure.", briefAr: "أُسس الأزهر بُعيد تأسيس القاهرة الفاطمية، وتطور من جامع إلى أحد أكثر مراكز التعلم تأثيراً في العالم الإسلامي. تسجّل عمارته الحالية أسرات حاكمة متعددة: إضافات فاطمية وأيوبية ومملوكية وعثمانية تبدو جلية في مآذنه المتراكبة وفنائه وفضاءاته التعليمية.", clarificationEn: "Al-Azhar's architecture spans many centuries and dynasties. It is a living institution, not a museum.", clarificationAr: "تمتد عمارة الأزهر عبر قرون وأسرات حاكمة متعددة. إنه مؤسسة حية لا متحف.", keyDates: [{ year: 970, labelEn: "Foundation by Jawhar al-Siqilli", labelAr: "التأسيس بيد جوهر الصقلي" }, { year: 988, labelEn: "First teaching circle established", labelAr: "أول حلقة تدريس" }], lat: "30.0459000", lng: "31.2628000", activeWorship: true, ticketed: false, photographyAllowed: "exterior_only" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Courtyard, layered minarets, teaching spaces", priorityVisualStoryAr: "الفناء والمآذن المتراكبة والفضاءات التعليمية", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Al-Azhar_Mosque.jpg/800px-Al-Azhar_Mosque.jpg", coverImageAlt: "Al-Azhar Mosque courtyard with its layered minarets, Cairo", coverImageAltAr: "فناء الجامع الأزهر ومآذنه المتراكبة بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "mosque-al-hakim", nameEn: "Mosque of al-Hakim bi-Amr Allah", nameAr: "جامع الحاكم بأمر الله", periodId: 4, districtId: 2, placeTypeId: 1, foundedYear: 990, foundedYearEnd: 1013, dateCertainty: "certain" as const, dateDisplayEn: "990–1013 CE", dateDisplayAr: "٩٩٠–١٠١٣م", patronEn: "Begun by Caliph al-Aziz; completed by al-Hakim bi-Amr Allah", patronAr: "بدأه الخليفة العزيز وأكمله الحاكم بأمر الله", originalFunctionEn: "Royal Fatimid congregational mosque", originalFunctionAr: "جامع فاطمي ملكي", currentFunctionEn: "Active mosque (Dawoodi Bohra community)", currentFunctionAr: "مسجد نشط (مجتمع البهرة الداوودية)", briefEn: "Begun by Caliph al-Aziz and completed by al-Hakim, this monumental mosque stood near Cairo's northern edge and was later incorporated into the expanded city walls. Its projecting entrance, large courtyard, and encased minarets are central to understanding Fatimid scale and defensive thinking. The mosque was restored in the twentieth century by the Dawoodi Bohra community and remains an active place of worship.", briefAr: "بدأه الخليفة العزيز وأكمله الحاكم، وقف هذا الجامع الضخم قرب الطرف الشمالي للقاهرة ثم أُدرج لاحقاً في أسوار المدينة الموسّعة. مدخله البارز وفناؤه الكبير ومآذنه المغلّفة محورية لفهم الحجم الفاطمي والتفكير الدفاعي.", keyDates: [{ year: 990, labelEn: "Construction begins under al-Aziz", labelAr: "بدء البناء في عهد العزيز" }, { year: 1013, labelEn: "Completed under al-Hakim", labelAr: "الاكتمال في عهد الحاكم" }], lat: "30.0524000", lng: "31.2618000", activeWorship: true, ticketed: false, photographyAllowed: "exterior_only" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Monumental entrance, corner minarets, courtyard", priorityVisualStoryAr: "المدخل الضخم والمآذن الزاوية والفناء", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Mosque_of_al-Hakim.jpg/800px-Mosque_of_al-Hakim.jpg", coverImageAlt: "The Mosque of al-Hakim with its encased minarets, Cairo", coverImageAltAr: "جامع الحاكم بمآذنه المغلّفة في القاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "bab-al-futuh", nameEn: "Bab al-Futuh", nameAr: "باب الفتوح", periodId: 4, districtId: 2, placeTypeId: 5, foundedYear: 1087, dateCertainty: "certain" as const, dateDisplayEn: "1087 CE", dateDisplayAr: "١٠٨٧م", patronEn: "Vizier Badr al-Jamali", patronAr: "الوزير بدر الجمالي", originalFunctionEn: "Northern defensive gate of Fatimid Cairo", originalFunctionAr: "البوابة الدفاعية الشمالية للقاهرة الفاطمية", currentFunctionEn: "Historic monument; accessible for visits", currentFunctionAr: "معلم تاريخي متاح للزيارة", briefEn: "The Gate of Conquests was built under the powerful vizier Badr al-Jamali as part of Cairo's stone fortifications. Rounded towers, defensive passages, carved stone details, and its alignment with al-Muizz Street make it both a military monument and a dramatic entrance into the medieval city. The gate can be entered and the wall walk explored, offering panoramic views over the historic city. Armenian stonemasons brought by Badr al-Jamali introduced new construction techniques that transformed Fatimid military architecture.", briefAr: "بُنيت بوابة الفتوح في عهد الوزير القوي بدر الجمالي ضمن تحصينات القاهرة الحجرية. أبراجها المستديرة وممراتها الدفاعية وتفاصيلها الحجرية المنحوتة ومحاذاتها لشارع المعز تجعلها معلماً عسكرياً ومدخلاً درامياً للمدينة الوسيطة.", keyDates: [{ year: 1087, labelEn: "Construction under Badr al-Jamali", labelAr: "البناء في عهد بدر الجمالي" }], lat: "30.0530000", lng: "31.2620000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Rounded towers, stone carving, wall walk", priorityVisualStoryAr: "الأبراج المستديرة والنحت الحجري وممشى السور", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bab_al-Futuh.jpg/800px-Bab_al-Futuh.jpg", coverImageAlt: "Bab al-Futuh, the northern Fatimid gate of Cairo", coverImageAltAr: "باب الفتوح، البوابة الفاطمية الشمالية للقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "bab-al-nasr", nameEn: "Bab al-Nasr", nameAr: "باب النصر", periodId: 4, districtId: 2, placeTypeId: 5, foundedYear: 1087, dateCertainty: "certain" as const, dateDisplayEn: "1087 CE", dateDisplayAr: "١٠٨٧م", patronEn: "Vizier Badr al-Jamali", patronAr: "الوزير بدر الجمالي", originalFunctionEn: "Northern defensive gate of Fatimid Cairo", originalFunctionAr: "البوابة الدفاعية الشمالية للقاهرة الفاطمية", currentFunctionEn: "Historic monument", currentFunctionAr: "معلم تاريخي", briefEn: "The Gate of Victory forms another major northern entrance through the Fatimid walls, built alongside Bab al-Futuh by Vizier Badr al-Jamali in 1087 CE. Its rectangular towers, shields and swords carved in stone, and later military use allow comparison of defensive symbolism and engineering with nearby Bab al-Futuh. The carved stone shields on the towers are among the most distinctive decorative elements in Fatimid military architecture.", briefAr: "تشكّل بوابة النصر مدخلاً شمالياً رئيسياً آخر عبر الأسوار الفاطمية، بُنيت جنباً إلى جنب مع باب الفتوح بيد الوزير بدر الجمالي عام ١٠٨٧م. أبراجها المستطيلة والدروع والسيوف المنحوتة في الحجر تتيح مقارنة الرمزية الدفاعية مع باب الفتوح المجاور.", keyDates: [{ year: 1087, labelEn: "Construction under Badr al-Jamali", labelAr: "البناء في عهد بدر الجمالي" }], lat: "30.0535000", lng: "31.2625000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 20, recommendedDurationMax: 45, priorityVisualStoryEn: "Rectangular towers, carved shields, wall masonry", priorityVisualStoryAr: "الأبراج المستطيلة والدروع المنحوتة وبنية السور", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Bab_al-Nasr.jpg/800px-Bab_al-Nasr.jpg", coverImageAlt: "Bab al-Nasr, the Gate of Victory in Fatimid Cairo", coverImageAltAr: "باب النصر في القاهرة الفاطمية", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "bab-zuweila", nameEn: "Bab Zuweila", nameAr: "باب زويلة", periodId: 4, districtId: 2, placeTypeId: 5, foundedYear: 1092, dateCertainty: "certain" as const, dateDisplayEn: "1092 CE; minarets of al-Mu'ayyad Mosque added c. 1420", dateDisplayAr: "١٠٩٢م؛ مآذن جامع المؤيد أُضيفت نحو ١٤٢٠م", patronEn: "Vizier Badr al-Jamali (gate); Sultan al-Mu'ayyad Shaykh (minarets)", patronAr: "الوزير بدر الجمالي (البوابة)؛ السلطان المؤيد شيخ (المآذن)", originalFunctionEn: "Southern defensive gate of Fatimid Cairo", originalFunctionAr: "البوابة الدفاعية الجنوبية للقاهرة الفاطمية", currentFunctionEn: "Historic monument; accessible for visits with rooftop views", currentFunctionAr: "معلم تاريخي متاح للزيارة مع إطلالات من السطح", briefEn: "This southern gate once controlled entry to Fatimid Cairo and later became the base for the twin minarets of the Mosque of al-Mu'ayyad Shaykh. It witnessed ceremonial processions, public punishments, and the final defeat of the Mamluk sultan Tumanbay in 1517, giving it an unusually dramatic urban biography. Visitors can climb to the rooftop for panoramic views over the historic city.", briefAr: "تحكّمت هذه البوابة الجنوبية في الدخول إلى القاهرة الفاطمية ثم أصبحت قاعدة للمآذن التوأم لجامع المؤيد شيخ. شهدت المواكب الاحتفالية والعقوبات العامة والهزيمة الأخيرة للسلطان المملوكي طومان باي عام ١٥١٧م.", keyDates: [{ year: 1092, labelEn: "Gate constructed under Badr al-Jamali", labelAr: "بناء البوابة في عهد بدر الجمالي" }, { year: 1517, labelEn: "Tumanbay hanged here — end of Mamluk rule", labelAr: "شنق طومان باي هنا — نهاية الحكم المملوكي" }], lat: "30.0430000", lng: "31.2596000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Gate arch, twin minarets, rooftop views", priorityVisualStoryAr: "قوس البوابة والمآذن التوأم والإطلالات من السطح", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Bab_Zuweila.jpg/800px-Bab_Zuweila.jpg", coverImageAlt: "Bab Zuweila with the twin minarets of al-Mu'ayyad Mosque, Cairo", coverImageAltAr: "باب زويلة مع مآذن جامع المؤيد التوأم بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-aqmar-mosque", nameEn: "Al-Aqmar Mosque", nameAr: "جامع الأقمر", periodId: 4, districtId: 2, placeTypeId: 1, foundedYear: 1125, dateCertainty: "certain" as const, dateDisplayEn: "1125 CE", dateDisplayAr: "١١٢٥م", patronEn: "Vizier al-Ma'mun al-Bata'ihi", patronAr: "الوزير المأمون البطائحي", originalFunctionEn: "Mosque", originalFunctionAr: "مسجد", currentFunctionEn: "Active mosque", currentFunctionAr: "مسجد نشط", briefEn: "Al-Aqmar is celebrated for one of Egypt's earliest surviving decorated stone mosque façades. Its builders aligned the façade with al-Muizz Street while orienting the prayer hall toward Mecca — a geometric problem solved through an angled interior plan. The carved stone medallions, muqarnas hood, and Kufic inscription bands make it a masterpiece of Fatimid decorative stonework. The name 'al-Aqmar' means 'the moonlit,' referring to the pale limestone that glows at night.", briefAr: "يُحتفى بالأقمر لكونه أحد أقدم واجهات المساجد الحجرية المزخرفة الباقية في مصر. واجه بناؤه الواجهة مع شارع المعز مع توجيه قاعة الصلاة نحو مكة، وهي مشكلة هندسية حُلّت بمخطط داخلي مائل.", keyDates: [{ year: 1125, labelEn: "Construction under al-Ma'mun al-Bata'ihi", labelAr: "البناء في عهد المأمون البطائحي" }], lat: "30.0498000", lng: "31.2622000", activeWorship: true, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 20, recommendedDurationMax: 40, priorityVisualStoryEn: "Carved façade, medallions, Kufic inscriptions", priorityVisualStoryAr: "الواجهة المنحوتة والمداليات والكتابات الكوفية", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Al-Aqmar_Mosque_facade.jpg/800px-Al-Aqmar_Mosque_facade.jpg", coverImageAlt: "The decorated stone façade of al-Aqmar Mosque on al-Muizz Street", coverImageAltAr: "الواجهة الحجرية المزخرفة لجامع الأقمر على شارع المعز", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "cairo-citadel", nameEn: "Cairo Citadel", nameAr: "قلعة صلاح الدين الأيوبي", periodId: 5, districtId: 4, placeTypeId: 6, foundedYear: 1176, dateCertainty: "approximate" as const, dateDisplayEn: "Begun c. 1176 CE; continuously developed through the 19th century", dateDisplayAr: "بدأ نحو ١١٧٦م؛ تطور باستمرار حتى القرن التاسع عشر", patronEn: "Salah al-Din (Saladin); later Mamluk, Ottoman, and Muhammad Ali additions", patronAr: "صلاح الدين؛ ثم إضافات مملوكية وعثمانية ومن أسرة محمد علي", originalFunctionEn: "Fortified seat of government", originalFunctionAr: "مقر الحكومة المحصّن", currentFunctionEn: "Historic monument, museums, and active mosque", currentFunctionAr: "معلم تاريخي ومتاحف ومسجد نشط", briefEn: "Initiated under Salah al-Din as a fortified seat above Cairo, the Citadel became a center of government for centuries. Its walls, palaces, mosques, wells, museums, and panoramic position should be presented as a changing political landscape rather than a single monument. Mamluk sultans rebuilt and expanded it; the Ottomans added their own structures; Muhammad Ali demolished much of the medieval fabric to build his great mosque. The Citadel is best understood as a palimpsest of power — each dynasty leaving its mark while erasing or adapting what came before.", briefAr: "أُسست القلعة في عهد صلاح الدين مقراً محصناً فوق القاهرة وأصبحت مركزاً للحكم لقرون. ينبغي تقديم أسوارها وقصورها ومساجدها وآبارها ومتاحفها ومشهدها البانورامي بوصفها مشهداً سياسياً متغيراً لا معلماً واحداً.", keyDates: [{ year: 1176, labelEn: "Construction begins under Salah al-Din", labelAr: "بدء البناء في عهد صلاح الدين" }, { year: 1848, labelEn: "Muhammad Ali Mosque completed", labelAr: "اكتمال جامع محمد علي" }], lat: "30.0287000", lng: "31.2597000", activeWorship: true, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 120, recommendedDurationMax: 240, priorityVisualStoryEn: "Fortifications, city panorama, layered mosques", priorityVisualStoryAr: "التحصينات وبانوراما المدينة والمساجد المتراكبة", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Cairo_Citadel.jpg/800px-Cairo_Citadel.jpg", coverImageAlt: "The Cairo Citadel with the Muhammad Ali Mosque dominating the skyline", coverImageAltAr: "قلعة القاهرة مع جامع محمد علي يهيمن على الأفق", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "qalawun-complex", nameEn: "Qalawun Complex", nameAr: "مجموعة السلطان المنصور قلاوون", periodId: 6, districtId: 2, placeTypeId: 4, foundedYear: 1284, foundedYearEnd: 1285, dateCertainty: "certain" as const, dateDisplayEn: "1284–1285 CE", dateDisplayAr: "١٢٨٤–١٢٨٥م", patronEn: "Sultan al-Mansur Qalawun", patronAr: "السلطان المنصور قلاوون", originalFunctionEn: "Mausoleum, madrasa, and hospital (bimaristan)", originalFunctionAr: "ضريح ومدرسة وبيمارستان", currentFunctionEn: "Historic monument; mausoleum active for visits", currentFunctionAr: "معلم تاريخي؛ الضريح متاح للزيارة", briefEn: "Built for Sultan al-Mansur Qalawun, the complex joined a mausoleum, madrasa, and celebrated hospital in the heart of Bayn al-Qasrayn. Its monumental street façade, colored marble inlay, stucco ornament, stained glass windows, and civic functions make it a central case study in Mamluk urban patronage. The hospital served patients regardless of religion or social status — a remarkable institution for its time.", briefAr: "بُنيت المجموعة للسلطان المنصور قلاوون وجمعت ضريحاً ومدرسة وبيمارستاناً مشهوراً في قلب بين القصرين. واجهتها الشارعية الضخمة وتطعيم الرخام الملوّن وزخارف الجص ونوافذ الزجاج الملوّن ووظائفها المدنية تجعلها دراسة حالة محورية في الرعاية الحضرية المملوكية.", keyDates: [{ year: 1284, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1285, labelEn: "Complex completed", labelAr: "اكتمال المجمع" }], lat: "30.0490000", lng: "31.2620000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 45, recommendedDurationMax: 90, priorityVisualStoryEn: "Street façade, mausoleum interior, marble, stained glass", priorityVisualStoryAr: "الواجهة الشارعية وداخل الضريح والرخام والزجاج الملوّن", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Qalawun_complex.jpg/800px-Qalawun_complex.jpg", coverImageAlt: "The monumental façade of the Qalawun Complex on al-Muizz Street", coverImageAltAr: "الواجهة الضخمة لمجموعة قلاوون على شارع المعز", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "sultan-hasan-mosque", nameEn: "Mosque and Madrasa of Sultan Hasan", nameAr: "مسجد ومدرسة السلطان حسن", periodId: 6, districtId: 4, placeTypeId: 4, foundedYear: 1356, foundedYearEnd: 1363, dateCertainty: "certain" as const, dateDisplayEn: "1356–1363 CE", dateDisplayAr: "١٣٥٦–١٣٦٣م", patronEn: "Sultan Hasan ibn Muhammad ibn Qalawun", patronAr: "السلطان حسن بن محمد بن قلاوون", originalFunctionEn: "Mosque, madrasa for four Sunni legal schools, and mausoleum", originalFunctionAr: "مسجد ومدرسة للمذاهب الفقهية الأربعة وضريح", currentFunctionEn: "Active mosque and historic monument", currentFunctionAr: "مسجد نشط ومعلم تاريخي", briefEn: "One of Cairo's grandest Mamluk monuments, the complex combines a dramatic recessed portal, immense cruciform courtyard, four teaching iwans for the Sunni legal schools, mausoleum, and soaring minarets. The stonework, stucco, woodwork, and marble represent the height of Bahri Mamluk craftsmanship. Sultan Hasan was murdered before the complex was completed, and his body was never placed in the mausoleum he built.", briefAr: "أحد أعظم المعالم المملوكية في القاهرة، يجمع المجمع بين مدخل غائر درامي وفناء مصلبي هائل وأربعة إيوانات تعليمية للمذاهب الفقهية السنية وضريح ومآذن شاهقة. تمثّل أعمال الحجر والجص والخشب والرخام ذروة الحرفية المملوكية البحرية.", keyDates: [{ year: 1356, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1361, labelEn: "Sultan Hasan murdered", labelAr: "مقتل السلطان حسن" }, { year: 1363, labelEn: "Complex completed posthumously", labelAr: "اكتمال المجمع بعد وفاته" }], lat: "30.0295000", lng: "31.2580000", activeWorship: true, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 60, recommendedDurationMax: 120, priorityVisualStoryEn: "Recessed portal, soaring iwan, courtyard, hanging lamps", priorityVisualStoryAr: "المدخل الغائر والإيوان الشاهق والفناء والمصابيح المعلقة", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Sultan_Hassan_Mosque.jpg/800px-Sultan_Hassan_Mosque.jpg", coverImageAlt: "The massive portal and minarets of Sultan Hasan Mosque, Cairo", coverImageAltAr: "المدخل الضخم ومآذن مسجد السلطان حسن بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-rifai-mosque", nameEn: "Al-Rifa'i Mosque", nameAr: "جامع الرفاعي", periodId: 10, districtId: 4, placeTypeId: 4, foundedYear: 1869, foundedYearEnd: 1912, dateCertainty: "certain" as const, dateDisplayEn: "Begun 1869; completed 1912", dateDisplayAr: "بدأ ١٨٦٩م؛ اكتمل ١٩١٢م", patronEn: "Princess Khushyar Hanim (begun); Khedive Abbas II (completed)", patronAr: "الأميرة خوشيار هانم (البداية)؛ الخديوي عباس الثاني (الاكتمال)", originalFunctionEn: "Royal mausoleum and mosque", originalFunctionAr: "ضريح ملكي ومسجد", currentFunctionEn: "Active mosque and royal mausoleum", currentFunctionAr: "مسجد نشط وضريح ملكي", briefEn: "Built opposite Sultan Hasan, al-Rifa'i combines a royal mausoleum, active religious significance, and a modern historicist interpretation of Islamic architectural traditions. The paired monuments allow a deep comparison between medieval Mamluk construction and later dynastic memory. Al-Rifa'i contains the tombs of the last Khedives of Egypt and the last Shah of Iran.", briefAr: "بُني الرفاعي أمام مسجد السلطان حسن ويجمع بين ضريح ملكي وأهمية دينية نشطة وتفسير تاريخاني حديث للتقاليد المعمارية الإسلامية. يتيح المعلمان المتقابلان مقارنة عميقة بين البناء المملوكي الوسيط والذاكرة الأسرية اللاحقة.", keyDates: [{ year: 1869, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1912, labelEn: "Mosque completed", labelAr: "اكتمال الجامع" }], lat: "30.0293000", lng: "31.2578000", activeWorship: true, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Paired skyline with Sultan Hasan, royal tombs", priorityVisualStoryAr: "الأفق المزدوج مع السلطان حسن والأضرحة الملكية", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Al-Rifa%27i_Mosque.jpg/800px-Al-Rifa%27i_Mosque.jpg", coverImageAlt: "Al-Rifa'i Mosque opposite Sultan Hasan, Cairo", coverImageAltAr: "جامع الرفاعي أمام مسجد السلطان حسن بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "muhammad-ali-mosque", nameEn: "Mosque of Muhammad Ali", nameAr: "جامع محمد علي", periodId: 10, districtId: 4, placeTypeId: 1, foundedYear: 1830, foundedYearEnd: 1848, dateCertainty: "approximate" as const, dateDisplayEn: "Constructed c. 1830–1848 CE", dateDisplayAr: "بُني نحو ١٨٣٠–١٨٤٨م", patronEn: "Muhammad Ali Pasha", patronAr: "محمد علي باشا", originalFunctionEn: "Royal mosque and mausoleum", originalFunctionAr: "مسجد ملكي وضريح", currentFunctionEn: "Active mosque and historic monument", currentFunctionAr: "مسجد نشط ومعلم تاريخي", briefEn: "Dominating the Citadel skyline, the mosque uses a large central dome, semi-domes, twin pencil minarets, and extensive alabaster-like stone paneling. It represents Muhammad Ali's new political order and offers a striking visual comparison with the Mamluk mosque of al-Nasir Muhammad nearby. Designed by the Greek-Ottoman architect Yusuf Bushnak, the mosque follows the Ottoman imperial style of Istanbul rather than Cairo's Mamluk tradition.", briefAr: "يهيمن الجامع على أفق القلعة بقبته المركزية الكبيرة وأنصاف قبابه ومآذنه القلمية التوأم وتبطينه الحجري الشبيه بالألباستر. يمثّل النظام السياسي الجديد لمحمد علي ويتيح مقارنة بصرية لافتة مع جامع الناصر محمد المملوكي القريب.", keyDates: [{ year: 1830, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1848, labelEn: "Mosque completed", labelAr: "اكتمال الجامع" }], lat: "30.0289000", lng: "31.2601000", activeWorship: true, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Skyline, dome cascade, twin minarets, city panorama", priorityVisualStoryAr: "الأفق وتتالي القباب والمآذن التوأم وبانوراما المدينة", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Muhammad_Ali_Mosque.jpg/800px-Muhammad_Ali_Mosque.jpg", coverImageAlt: "The Muhammad Ali Mosque dominating the Citadel of Cairo", coverImageAltAr: "جامع محمد علي يهيمن على قلعة القاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "bayt-al-suhaymi", nameEn: "Bayt al-Suhaymi", nameAr: "بيت السحيمي", periodId: 9, districtId: 2, placeTypeId: 8, foundedYear: 1648, dateCertainty: "approximate" as const, dateDisplayEn: "Core structure c. 1648 CE; later additions", dateDisplayAr: "الهيكل الأساسي نحو ١٦٤٨م؛ إضافات لاحقة", patronEn: "Abd al-Wahab al-Tablawy (1648 section)", patronAr: "عبد الوهاب الطبلاوي (قسم ١٦٤٨م)", originalFunctionEn: "Elite urban residence", originalFunctionAr: "مسكن حضري للنخبة", currentFunctionEn: "Museum and cultural venue", currentFunctionAr: "متحف وفضاء ثقافي", briefEn: "This richly preserved historic house reveals reception halls, multiple courtyards, mashrabiya screens, service areas, and climate-responsive domestic design. It is one of the best-preserved examples of Ottoman-period domestic architecture in Cairo. The mashrabiya screens filter light and air while maintaining privacy — a sophisticated solution to Cairo's climate and social norms.", briefAr: "يكشف هذا البيت التاريخي المحفوظ بشكل رائع عن قاعات الاستقبال والأفنية المتعددة والمشربيات ومناطق الخدمة والتصميم المنزلي المتكيّف مع المناخ. يُعدّ أحد أفضل الأمثلة المحفوظة على العمارة المنزلية في عصر القاهرة العثمانية.", keyDates: [{ year: 1648, labelEn: "First section built", labelAr: "بناء القسم الأول" }, { year: 1796, labelEn: "Second section added", labelAr: "إضافة القسم الثاني" }], lat: "30.0503000", lng: "31.2625000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 45, recommendedDurationMax: 90, priorityVisualStoryEn: "Mashrabiya screens, qa'a reception hall, courtyards", priorityVisualStoryAr: "المشربيات وقاعة الاستقبال والأفنية", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bayt_al-Suhaymi.jpg/800px-Bayt_al-Suhaymi.jpg", coverImageAlt: "The courtyard and mashrabiya screens of Bayt al-Suhaymi, Cairo", coverImageAltAr: "فناء بيت السحيمي ومشربياته بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "museum-islamic-art", nameEn: "Museum of Islamic Art", nameAr: "متحف الفن الإسلامي", periodId: 11, districtId: 2, placeTypeId: 11, foundedYear: 1903, dateCertainty: "certain" as const, dateDisplayEn: "Collection formed 19th century; museum building 1903", dateDisplayAr: "تشكّلت المجموعة في القرن التاسع عشر؛ مبنى المتحف ١٩٠٣م", patronEn: "Egyptian state collection", patronAr: "المجموعة الحكومية المصرية", originalFunctionEn: "Museum of Islamic art and material culture", originalFunctionAr: "متحف الفن الإسلامي والثقافة المادية", currentFunctionEn: "Museum (reopened after 2014 restoration)", currentFunctionAr: "متحف (أُعيد افتتاحه بعد ترميم ٢٠١٤م)", briefEn: "The museum brings together manuscripts, woodwork, ceramics, glass, metalwork, textiles, stone, and scientific instruments from Egypt and the wider Islamic world. It functions as the material-learning hub for understanding details seen across the city — the carved wood of a minbar, the geometry of a ceramic tile, the calligraphy of an inscription band. The collection was severely damaged in 2014 by a car bomb and has been substantially restored.", briefAr: "يجمع المتحف المخطوطات والأخشاب والخزف والزجاج والمعادن والمنسوجات والحجر والأدوات العلمية من مصر والعالم الإسلامي الأوسع. يعمل بوصفه مركز التعلم المادي لفهم التفاصيل المرئية في أرجاء المدينة.", keyDates: [{ year: 1903, labelEn: "Current museum building opened", labelAr: "افتتاح مبنى المتحف الحالي" }, { year: 2014, labelEn: "Damaged by car bomb; restoration begins", labelAr: "تضرر بسيارة مفخخة؛ بدء الترميم" }], lat: "30.0468000", lng: "31.2490000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 90, recommendedDurationMax: 180, priorityVisualStoryEn: "Object galleries, pattern comparison, conservation", priorityVisualStoryAr: "قاعات الأشياء ومقارنة الأنماط والترميم", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Museum_of_Islamic_Art_Cairo.jpg/800px-Museum_of_Islamic_Art_Cairo.jpg", coverImageAlt: "The Museum of Islamic Art building in Cairo", coverImageAltAr: "مبنى متحف الفن الإسلامي في القاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-muizz-street", nameEn: "Al-Muizz Street", nameAr: "شارع المعز لدين الله الفاطمي", periodId: 4, districtId: 2, placeTypeId: 12, foundedYear: 969, dateCertainty: "certain" as const, dateDisplayEn: "Established as Fatimid city axis from 969 CE", dateDisplayAr: "أُسس محوراً للمدينة الفاطمية من ٩٦٩م", patronEn: "Multiple patrons across ten centuries", patronAr: "رعاة متعددون عبر عشرة قرون", originalFunctionEn: "Ceremonial and commercial spine of Fatimid Cairo", originalFunctionAr: "العمود الفقري الاحتفالي والتجاري للقاهرة الفاطمية", currentFunctionEn: "Pedestrianized heritage street with active commerce and worship", currentFunctionAr: "شارع تراثي للمشاة مع تجارة نشطة وعبادة", briefEn: "Running between the northern and southern Fatimid gates, al-Muizz became a ceremonial, commercial, religious, and residential spine over ten centuries. The street should be treated as a sequence of urban rooms rather than one attraction — monuments, shops, homes, and crowds coexist in a living urban fabric. The street contains more than a dozen major monuments from the Fatimid, Ayyubid, Mamluk, and Ottoman periods within a few hundred meters.", briefAr: "يمتد شارع المعز بين البوابتين الفاطميتين الشمالية والجنوبية وأصبح على مدى عشرة قرون عموداً فقرياً احتفالياً وتجارياً ودينياً وسكنياً. ينبغي التعامل مع الشارع بوصفه تسلسلاً من الغرف الحضرية لا معلماً واحداً.", keyDates: [{ year: 969, labelEn: "Established as Fatimid city axis", labelAr: "إنشاؤه محوراً للمدينة الفاطمية" }], lat: "30.0490000", lng: "31.2620000", activeWorship: true, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 90, recommendedDurationMax: 240, priorityVisualStoryEn: "Continuous street scroll, monument clusters, day/night life", priorityVisualStoryAr: "التمرير المستمر للشارع وتجمعات المعالم والحياة نهاراً وليلاً", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Al-Muizz_Street.jpg/800px-Al-Muizz_Street.jpg", coverImageAlt: "Al-Muizz Street with historic monuments and daily life, Cairo", coverImageAltAr: "شارع المعز بمعالمه التاريخية والحياة اليومية بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "khan-al-khalili", nameEn: "Khan al-Khalili", nameAr: "خان الخليلي", periodId: 7, districtId: 6, placeTypeId: 16, foundedYear: 1382, dateCertainty: "approximate" as const, dateDisplayEn: "Market district developed from the late 14th century", dateDisplayAr: "تطور حي السوق من أواخر القرن الرابع عشر", patronEn: "Amir Jarkas al-Khalili (original khan)", patronAr: "الأمير جركس الخليلي (الخان الأصلي)", originalFunctionEn: "Commercial khan (caravanserai)", originalFunctionAr: "خان تجاري", currentFunctionEn: "Living market district with crafts, tourism, and neighborhood commerce", currentFunctionAr: "حي سوق حي بالحرف والسياحة وتجارة الحي", briefEn: "Established as a commercial khan and repeatedly transformed, Khan al-Khalili is now a living market district tied to al-Hussein and al-Azhar. Its story must avoid treating commerce as staged folklore and instead show changing trade, craft, tourism, and neighborhood life. The original khan was built on the site of a Fatimid royal cemetery — a deliberate act of political erasure by the Mamluk amir.", briefAr: "أُسس خان تجارياً وتحوّل مرات عديدة، وهو الآن حي سوق حي مرتبط بالحسين والأزهر. يجب أن تتجنب قصته معاملة التجارة بوصفها فولكلوراً مُخرَجاً وأن تُظهر بدلاً من ذلك التجارة والحرف والسياحة والحياة الحضرية المتغيرة.", keyDates: [{ year: 1382, labelEn: "Original khan established by Jarkas al-Khalili", labelAr: "إنشاء الخان الأصلي بيد جركس الخليلي" }], lat: "30.0468000", lng: "31.2634000", activeWorship: false, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 60, recommendedDurationMax: 180, priorityVisualStoryEn: "Market passages, shopfronts, craft details", priorityVisualStoryAr: "ممرات السوق وواجهات المحلات وتفاصيل الحرف", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Khan_al-Khalili.jpg/800px-Khan_al-Khalili.jpg", coverImageAlt: "The historic market passages of Khan al-Khalili, Cairo", coverImageAltAr: "ممرات سوق خان الخليلي التاريخية بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "barquq-complex", nameEn: "Madrasa and Khanqah of Sultan Barquq", nameAr: "مدرسة وخانقاه السلطان الظاهر برقوق", periodId: 7, districtId: 2, placeTypeId: 4, foundedYear: 1384, foundedYearEnd: 1386, dateCertainty: "certain" as const, dateDisplayEn: "1384–1386 CE", dateDisplayAr: "١٣٨٤–١٣٨٦م", patronEn: "Sultan al-Zahir Barquq, first Burji Mamluk sultan", patronAr: "السلطان الظاهر برقوق، أول سلاطين المماليك البرجية", originalFunctionEn: "Mosque, madrasa, khanqah, and mausoleum", originalFunctionAr: "مسجد ومدرسة وخانقاه وضريح", currentFunctionEn: "Active mosque and historic monument", currentFunctionAr: "مسجد نشط ومعلم تاريخي", briefEn: "Barquq's complex completed the great monumental composition at Bayn al-Qasrayn. It combined mosque, madrasa, Sufi khanqah, mausoleum, student rooms, and service spaces — making it an excellent visual lesson in the multifunctional Mamluk foundation. As the first Burji Mamluk sultan, Barquq used this complex to legitimize his rule through architectural display.", briefAr: "أكمل مجمع برقوق التأليف الضخم الكبير في بين القصرين. جمع مسجداً ومدرسة وخانقاهاً صوفية وضريحاً وغرفاً للطلاب ومساحات خدمية، مما يجعله درساً بصرياً ممتازاً في التأسيس المملوكي متعدد الوظائف.", keyDates: [{ year: 1384, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1386, labelEn: "Complex completed", labelAr: "اكتمال المجمع" }], lat: "30.0492000", lng: "31.2622000", activeWorship: true, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 30, recommendedDurationMax: 60, priorityVisualStoryEn: "Bayn al-Qasrayn ensemble, courtyard, marble, dome", priorityVisualStoryAr: "مجموعة بين القصرين والفناء والرخام والقبة", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Barquq_complex.jpg/800px-Barquq_complex.jpg", coverImageAlt: "The façade of Sultan Barquq's complex at Bayn al-Qasrayn", coverImageAltAr: "واجهة مجمع السلطان برقوق في بين القصرين", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "faraj-ibn-barquq-khanqah", nameEn: "Khanqah and Mosque of Faraj ibn Barquq", nameAr: "خانقاه ومسجد فرج بن برقوق", periodId: 7, districtId: 5, placeTypeId: 4, foundedYear: 1400, foundedYearEnd: 1411, dateCertainty: "certain" as const, dateDisplayEn: "1400–1411 CE", dateDisplayAr: "١٤٠٠–١٤١١م", patronEn: "Sultan Faraj ibn Barquq", patronAr: "السلطان فرج بن برقوق", originalFunctionEn: "Khanqah (Sufi lodge), mosque, and mausoleum", originalFunctionAr: "خانقاه صوفية ومسجد وضريح", currentFunctionEn: "Historic monument in the Northern Cemetery", currentFunctionAr: "معلم تاريخي في القرافة الشمالية", briefEn: "Set within the Northern Cemetery, the complex is one of Cairo's most powerful Mamluk compositions, with twin domes, twin minarets, a courtyard, and residential cells for Sufi residents. The twin carved stone domes are among the finest examples of Mamluk dome decoration, their geometric and floral patterns visible from a great distance.", briefAr: "يقع المجمع في القرافة الشمالية وهو أحد أقوى التأليفات المملوكية في القاهرة بقبتيه التوأم ومآذنه التوأم وفنائه وخلاياه السكنية للمقيمين الصوفيين.", keyDates: [{ year: 1400, labelEn: "Construction begins", labelAr: "بدء البناء" }, { year: 1411, labelEn: "Complex completed", labelAr: "اكتمال المجمع" }], lat: "30.0550000", lng: "31.2780000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, funerarySensitive: true, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 45, recommendedDurationMax: 90, priorityVisualStoryEn: "Twin domes, twin minarets, funerary landscape", priorityVisualStoryAr: "القبتان التوأم والمآذن التوأم والمشهد الجنائزي", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Faraj_ibn_Barquq.jpg/800px-Faraj_ibn_Barquq.jpg", coverImageAlt: "The twin domes of Faraj ibn Barquq's complex in the Northern Cemetery", coverImageAltAr: "قبتا مجمع فرج بن برقوق التوأم في القرافة الشمالية", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "sabil-abd-al-rahman-katkhuda", nameEn: "Sabil-Kuttab of Abd al-Rahman Katkhuda", nameAr: "سبيل وكتاب عبد الرحمن كتخدا", periodId: 9, districtId: 2, placeTypeId: 9, foundedYear: 1744, dateCertainty: "certain" as const, dateDisplayEn: "1744 CE", dateDisplayAr: "١٧٤٤م", patronEn: "Abd al-Rahman Katkhuda", patronAr: "عبد الرحمن كتخدا", originalFunctionEn: "Public water fountain (sabil) with school above (kuttab)", originalFunctionAr: "نافورة مياه عامة (سبيل) مع مدرسة فوقها (كتاب)", currentFunctionEn: "Historic monument", currentFunctionAr: "معلم تاريخي", briefEn: "This elegant corner building combined a public water fountain below with a school for children above. Its projecting form, ceramic tiles, copper grilles, marble basins, and charitable purpose make it one of the clearest examples of architecture serving the street. The sabil-kuttab type — combining water charity with education — represents a distinctly Egyptian Islamic building tradition that flourished under the Mamluks and Ottomans.", briefAr: "جمع هذا المبنى الزاوي الأنيق نافورة مياه عامة في الأسفل ومدرسة للأطفال في الأعلى. شكله البارز وبلاطه الخزفي وشبابيكه النحاسية وأحواضه الرخامية وغرضه الخيري تجعله أحد أوضح الأمثلة على العمارة في خدمة الشارع.", keyDates: [{ year: 1744, labelEn: "Construction by Abd al-Rahman Katkhuda", labelAr: "البناء بيد عبد الرحمن كتخدا" }], lat: "30.0510000", lng: "31.2620000", activeWorship: false, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 15, recommendedDurationMax: 30, priorityVisualStoryEn: "Corner composition, copper windows, tiles, water basins", priorityVisualStoryAr: "التأليف الزاوي والنوافذ النحاسية والبلاط وأحواض المياه", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Sabil_Abd_al-Rahman_Katkhuda.jpg/800px-Sabil_Abd_al-Rahman_Katkhuda.jpg", coverImageAlt: "The corner sabil-kuttab of Abd al-Rahman Katkhuda on al-Muizz Street", coverImageAltAr: "سبيل وكتاب عبد الرحمن كتخدا الزاوي على شارع المعز", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-azhar-park", nameEn: "Al-Azhar Park", nameAr: "حديقة الأزهر", periodId: 11, districtId: 3, placeTypeId: 15, foundedYear: 2005, dateCertainty: "certain" as const, dateDisplayEn: "Opened 2005", dateDisplayAr: "افتُتحت ٢٠٠٥م", patronEn: "Aga Khan Trust for Culture", patronAr: "صندوق الآغا خان للثقافة", originalFunctionEn: "Public park on former rubble mound", originalFunctionAr: "حديقة عامة على تل ردم سابق", currentFunctionEn: "Public park, cultural venue, and conservation viewpoint", currentFunctionAr: "حديقة عامة وفضاء ثقافي ونقطة مشاهدة للتراث", briefEn: "Created on a former rubble mound beside Historic Cairo, the park provides major views toward the Citadel and restored sections of the Ayyubid wall. It is a contemporary chapter in the story of conservation, public space, landscape, and urban regeneration. The Aga Khan Trust for Culture not only created the park but also funded the restoration of the adjacent Ayyubid wall and supported community development in the neighboring Darb al-Ahmar district.", briefAr: "أُنشئت الحديقة على تل ردم سابق بجوار القاهرة التاريخية وتوفر إطلالات رئيسية نحو القلعة وأقسام مرمّمة من السور الأيوبي. إنها فصل معاصر في قصة الصون والفضاء العام والمشهد الطبيعي وإعادة التطوير الحضري.", keyDates: [{ year: 2005, labelEn: "Park opens to public", labelAr: "افتتاح الحديقة للعموم" }], lat: "30.0430000", lng: "31.2680000", activeWorship: false, ticketed: true, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 60, recommendedDurationMax: 120, priorityVisualStoryEn: "Panoramas, wall restoration, gardens, sunset skyline", priorityVisualStoryAr: "البانوراما وترميم السور والحدائق وأفق الغروب", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Al-Azhar_Park_Cairo.jpg/800px-Al-Azhar_Park_Cairo.jpg", coverImageAlt: "Al-Azhar Park with views toward the Citadel of Cairo", coverImageAltAr: "حديقة الأزهر مع إطلالات نحو قلعة القاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "al-hussein-mosque", nameEn: "Al-Hussein Mosque and District", nameAr: "مسجد وميدان الإمام الحسين", periodId: 4, districtId: 6, placeTypeId: 17, foundedYear: 1154, dateCertainty: "approximate" as const, dateDisplayEn: "Shrine tradition from 1154 CE; current architecture substantially later", dateDisplayAr: "تقليد الضريح من ١١٥٤م؛ العمارة الحالية لاحقة جوهرياً", patronEn: "Multiple patrons; current building largely 19th–20th century", patronAr: "رعاة متعددون؛ المبنى الحالي في معظمه من القرن التاسع عشر والعشرين", originalFunctionEn: "Shrine and mosque", originalFunctionAr: "مقام ومسجد", currentFunctionEn: "Active place of worship and devotion; major religious center", currentFunctionAr: "مكان عبادة وتبجيل نشط؛ مركز ديني رئيسي", briefEn: "Al-Hussein is one of Cairo's most important active devotional centers and anchors a dense district of markets, religious institutions, and public life. The app must distinguish documented architectural history, religious tradition, and current worship while avoiding invasive visitor behavior. This is an active sacred site where photography inside is not appropriate.", briefAr: "الحسين أحد أهم مراكز التبجيل النشطة في القاهرة ويرسّخ حياً كثيفاً من الأسواق والمؤسسات الدينية والحياة العامة. يجب أن يميّز التطبيق بين التاريخ المعماري الموثق والتقليد الديني والعبادة الحالية مع تجنب السلوك الاستفزازي للزوار.", keyDates: [{ year: 1154, labelEn: "Fatimid shrine established", labelAr: "إنشاء الضريح الفاطمي" }], lat: "30.0463000", lng: "31.2632000", activeWorship: true, ticketed: false, photographyAllowed: "no" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 20, recommendedDurationMax: 40, priorityVisualStoryEn: "Exterior and square, respectful crowd context", priorityVisualStoryAr: "الخارج والميدان وسياق الحشود المحترم", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Al-Hussein_Mosque.jpg/800px-Al-Hussein_Mosque.jpg", coverImageAlt: "Al-Hussein Mosque and square, an active devotional center in Cairo", coverImageAltAr: "مسجد وميدان الحسين، مركز تبجيل نشط في القاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
    { slug: "bayn-al-qasrayn", nameEn: "Bayn al-Qasrayn", nameAr: "بين القصرين", periodId: 4, districtId: 2, placeTypeId: 12, foundedYear: 969, dateCertainty: "certain" as const, dateDisplayEn: "Fatimid palace zone from 969 CE; Mamluk monumental avenue from 13th century", dateDisplayAr: "منطقة القصور الفاطمية من ٩٦٩م؛ شارع ضخم مملوكي من القرن الثالث عشر", patronEn: "Fatimid caliphs (palaces); Mamluk sultans (monuments)", patronAr: "الخلفاء الفاطميون (القصور)؛ السلاطين المماليك (المعالم)", originalFunctionEn: "Space between two Fatimid royal palaces", originalFunctionAr: "الفضاء بين قصرين ملكيين فاطميين", currentFunctionEn: "Historic street with major Mamluk monuments", currentFunctionAr: "شارع تاريخي بمعالم مملوكية كبرى", briefEn: "Once the space between two Fatimid palaces, Bayn al-Qasrayn later became the setting for major Ayyubid and Mamluk foundations. It is the best place to visualize political replacement, inherited urban memory, and the competition of monumental façades. The Qalawun, al-Nasir Muhammad, and Barquq complexes face each other across this narrow street, creating one of the most concentrated sequences of medieval Islamic architecture anywhere.", briefAr: "كان فضاءً بين قصرين فاطميين ثم أصبح لاحقاً موضعاً للتأسيسات الأيوبية والمملوكية الكبرى. إنه أفضل مكان لتصوير الإحلال السياسي والذاكرة الحضرية الموروثة وتنافس الواجهات الضخمة.", keyDates: [{ year: 969, labelEn: "Fatimid palaces established", labelAr: "إنشاء القصور الفاطمية" }, { year: 1285, labelEn: "Qalawun complex completed", labelAr: "اكتمال مجمع قلاوون" }], lat: "30.0490000", lng: "31.2620000", activeWorship: false, ticketed: false, photographyAllowed: "yes" as const, status: "published" as const, publishedAt: new Date(), recommendedDurationMin: 60, recommendedDurationMax: 120, priorityVisualStoryEn: "Street elevation, vanished palaces overlay, Qalawun-Barquq sequence", priorityVisualStoryAr: "ارتفاع الشارع وطبقة القصور المختفية وتسلسل قلاوون-برقوق", coverImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Bayn_al-Qasrayn.jpg/800px-Bayn_al-Qasrayn.jpg", coverImageAlt: "The monumental façades of Bayn al-Qasrayn, Cairo", coverImageAltAr: "الواجهات الضخمة لبين القصرين بالقاهرة", coverImageAttribution: "Wikimedia Commons / CC BY-SA", coverImageLicense: "CC BY-SA" },
  ];

  for (const place of placesData) {
    await db.insert(places).ignore().values(place as any);
  }

  // WALKS
  console.log("  → Seeding 18 walks...");
  const walksData = [
    { slug: "fustat-early-islamic", nameEn: "Fustat and the Earliest Islamic City", nameAr: "الفسطاط وأقدم مدينة إسلامية", descriptionEn: "Explore the foundations of Islamic Cairo in Fustat, including the Mosque of Amr ibn al-As and the Nilometer.", descriptionAr: "استكشف أسس القاهرة الإسلامية في الفسطاط، بما فيها جامع عمرو بن العاص ومقياس النيل.", durationMinutes: 150, distanceMeters: 4000, difficulty: "moderate" as const, stops: [{placeSlug: "mosque-amr-ibn-al-as", order: 1}, {placeSlug: "nilometer-roda", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 1 },
    { slug: "ibn-tulun-saliba", nameEn: "Ibn Tulun, al-Saliba, and the Mamluk Neighborhood", nameAr: "ابن طولون والصليبة والحي المملوكي", descriptionEn: "Walk from the Tulunid mosque through the Mamluk complexes of al-Saliba Street to the Citadel.", descriptionAr: "تجوّل من الجامع الطولوني عبر المجمعات المملوكية في شارع الصليبة إلى القلعة.", durationMinutes: 180, distanceMeters: 3500, difficulty: "easy" as const, stops: [{placeSlug: "mosque-ibn-tulun", order: 1}, {placeSlug: "cairo-citadel", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 2 },
    { slug: "fatimid-gates-walls", nameEn: "Fatimid Gates and City Walls", nameAr: "بوابات القاهرة الفاطمية وأسوارها", descriptionEn: "Walk the northern walls of Fatimid Cairo from Bab al-Futuh to Bab al-Nasr, then south to Bab Zuweila.", descriptionAr: "تجوّل على الأسوار الشمالية للقاهرة الفاطمية من باب الفتوح إلى باب النصر ثم جنوباً إلى باب زويلة.", durationMinutes: 120, distanceMeters: 2500, difficulty: "easy" as const, stops: [{placeSlug: "bab-al-futuh", order: 1}, {placeSlug: "bab-al-nasr", order: 2}, {placeSlug: "bab-zuweila", order: 3}], hasStaleInfo: false, status: "published" as const, sortOrder: 3 },
    { slug: "al-muizz-full", nameEn: "Al-Muizz Street: Ten Centuries in One Walk", nameAr: "شارع المعز: عشرة قرون في جولة واحدة", descriptionEn: "Walk the full length of al-Muizz Street from Bab al-Futuh to Bab Zuweila, stopping at major monuments.", descriptionAr: "تجوّل على امتداد شارع المعز كاملاً من باب الفتوح إلى باب زويلة مع التوقف عند المعالم الكبرى.", durationMinutes: 240, distanceMeters: 1200, difficulty: "easy" as const, stops: [{placeSlug: "bab-al-futuh", order: 1}, {placeSlug: "mosque-al-hakim", order: 2}, {placeSlug: "sabil-abd-al-rahman-katkhuda", order: 3}, {placeSlug: "al-aqmar-mosque", order: 4}, {placeSlug: "bayn-al-qasrayn", order: 5}, {placeSlug: "barquq-complex", order: 6}, {placeSlug: "qalawun-complex", order: 7}, {placeSlug: "bab-zuweila", order: 8}], hasStaleInfo: false, status: "published" as const, sortOrder: 4 },
    { slug: "bayn-al-qasrayn-mamluk", nameEn: "Bayn al-Qasrayn: The Mamluk Monumental Avenue", nameAr: "بين القصرين: الشارع الضخم المملوكي", descriptionEn: "Focus on the dense sequence of Mamluk royal complexes at Bayn al-Qasrayn.", descriptionAr: "ركّز على التسلسل الكثيف للمجمعات الملكية المملوكية في بين القصرين.", durationMinutes: 150, distanceMeters: 600, difficulty: "easy" as const, stops: [{placeSlug: "barquq-complex", order: 1}, {placeSlug: "qalawun-complex", order: 2}, {placeSlug: "bayn-al-qasrayn", order: 3}], hasStaleInfo: false, status: "published" as const, sortOrder: 5 },
    { slug: "citadel-sultan-hasan", nameEn: "The Citadel and the Mamluk Giants", nameAr: "القلعة وعمالقة المماليك", descriptionEn: "Visit the Citadel and the paired monuments of Sultan Hasan and al-Rifa'i below.", descriptionAr: "زُر القلعة والمعلمين المتقابلين السلطان حسن والرفاعي أسفلها.", durationMinutes: 180, distanceMeters: 2000, difficulty: "moderate" as const, stops: [{placeSlug: "sultan-hasan-mosque", order: 1}, {placeSlug: "al-rifai-mosque", order: 2}, {placeSlug: "cairo-citadel", order: 3}, {placeSlug: "muhammad-ali-mosque", order: 4}], hasStaleInfo: false, status: "published" as const, sortOrder: 6 },
    { slug: "northern-cemetery-walk", nameEn: "The Northern Cemetery: Mamluk Funerary Landscape", nameAr: "القرافة الشمالية: المشهد الجنائزي المملوكي", descriptionEn: "Explore the major Mamluk mausoleums of the Northern Cemetery with sensitivity to the living community.", descriptionAr: "استكشف الأضرحة المملوكية الكبرى في القرافة الشمالية مع الحساسية تجاه المجتمع الحي.", durationMinutes: 180, distanceMeters: 3000, difficulty: "moderate" as const, stops: [{placeSlug: "faraj-ibn-barquq-khanqah", order: 1}], hasStaleInfo: false, requiresFuneraryApproval: true, status: "published" as const, sortOrder: 7 },
    { slug: "al-azhar-hussein-market", nameEn: "Al-Azhar, Al-Hussein, and Khan al-Khalili", nameAr: "الأزهر والحسين وخان الخليلي", descriptionEn: "Explore the religious and commercial heart of Islamic Cairo around al-Azhar and al-Hussein.", descriptionAr: "استكشف القلب الديني والتجاري للقاهرة الإسلامية حول الأزهر والحسين.", durationMinutes: 180, distanceMeters: 1500, difficulty: "easy" as const, stops: [{placeSlug: "al-azhar-mosque", order: 1}, {placeSlug: "al-hussein-mosque", order: 2}, {placeSlug: "khan-al-khalili", order: 3}], hasStaleInfo: false, status: "published" as const, sortOrder: 8 },
    { slug: "ottoman-domestic", nameEn: "Ottoman Domestic Life: Houses and Sabils", nameAr: "الحياة المنزلية العثمانية: البيوت والسبل", descriptionEn: "Explore Ottoman-period domestic architecture through Bayt al-Suhaymi and the sabils of al-Muizz Street.", descriptionAr: "استكشف العمارة المنزلية في العصر العثماني عبر بيت السحيمي وسبل شارع المعز.", durationMinutes: 150, distanceMeters: 2000, difficulty: "easy" as const, stops: [{placeSlug: "bayt-al-suhaymi", order: 1}, {placeSlug: "sabil-abd-al-rahman-katkhuda", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 9 },
    { slug: "darb-al-ahmar-living", nameEn: "Darb al-Ahmar: Living Heritage", nameAr: "الدرب الأحمر: التراث الحي", descriptionEn: "Walk through Darb al-Ahmar, a living historic district with conservation projects and active community life.", descriptionAr: "تجوّل في الدرب الأحمر، حي تاريخي حي يضم مشاريع صون وحياة مجتمعية نشطة.", durationMinutes: 150, distanceMeters: 2500, difficulty: "easy" as const, stops: [{placeSlug: "al-azhar-park", order: 1}], hasStaleInfo: false, status: "published" as const, sortOrder: 10 },
    { slug: "museum-monuments", nameEn: "Museum to Monuments: Material Culture Walk", nameAr: "من المتحف إلى المعالم: جولة الثقافة المادية", descriptionEn: "Start at the Museum of Islamic Art, then walk to al-Muizz to see the objects in their original contexts.", descriptionAr: "ابدأ من متحف الفن الإسلامي ثم تجوّل إلى شارع المعز لمشاهدة الأشياء في سياقاتها الأصلية.", durationMinutes: 210, distanceMeters: 3000, difficulty: "easy" as const, stops: [{placeSlug: "museum-islamic-art", order: 1}, {placeSlug: "al-muizz-street", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 11 },
    { slug: "fatimid-al-azhar-founding", nameEn: "The Fatimid City: Foundation and Faith", nameAr: "المدينة الفاطمية: التأسيس والإيمان", descriptionEn: "Trace the founding of al-Qahira through al-Azhar, al-Aqmar, and the Fatimid gates.", descriptionAr: "تتبّع تأسيس القاهرة عبر الأزهر والأقمر والبوابات الفاطمية.", durationMinutes: 180, distanceMeters: 2000, difficulty: "easy" as const, stops: [{placeSlug: "al-azhar-mosque", order: 1}, {placeSlug: "al-aqmar-mosque", order: 2}, {placeSlug: "mosque-al-hakim", order: 3}, {placeSlug: "bab-al-futuh", order: 4}], hasStaleInfo: false, status: "published" as const, sortOrder: 12 },
    { slug: "ayyubid-citadel-walls", nameEn: "Salah al-Din's Cairo: Citadel and Walls", nameAr: "قاهرة صلاح الدين: القلعة والأسوار", descriptionEn: "Explore the Ayyubid defensive landscape from the Citadel to the restored sections of the city walls.", descriptionAr: "استكشف المشهد الدفاعي الأيوبي من القلعة إلى الأقسام المرمّمة من أسوار المدينة.", durationMinutes: 180, distanceMeters: 3000, difficulty: "moderate" as const, stops: [{placeSlug: "cairo-citadel", order: 1}, {placeSlug: "al-azhar-park", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 13 },
    { slug: "mamluk-domes-minarets", nameEn: "Mamluk Domes and Minarets: A Visual Survey", nameAr: "قباب المماليك ومآذنهم: مسح بصري", descriptionEn: "A focused walk comparing Mamluk dome and minaret types across the historic city.", descriptionAr: "جولة مركّزة لمقارنة أنواع القباب والمآذن المملوكية في المدينة التاريخية.", durationMinutes: 180, distanceMeters: 3500, difficulty: "moderate" as const, stops: [{placeSlug: "qalawun-complex", order: 1}, {placeSlug: "barquq-complex", order: 2}, {placeSlug: "sultan-hasan-mosque", order: 3}, {placeSlug: "faraj-ibn-barquq-khanqah", order: 4}], hasStaleInfo: false, status: "published" as const, sortOrder: 14 },
    { slug: "conservation-regeneration", nameEn: "Conservation and Regeneration in Historic Cairo", nameAr: "الصون وإعادة التطوير في القاهرة التاريخية", descriptionEn: "Explore contemporary conservation efforts from al-Azhar Park to Darb al-Ahmar.", descriptionAr: "استكشف جهود الصون المعاصرة من حديقة الأزهر إلى الدرب الأحمر.", durationMinutes: 180, distanceMeters: 3000, difficulty: "easy" as const, stops: [{placeSlug: "al-azhar-park", order: 1}], hasStaleInfo: false, status: "published" as const, sortOrder: 15 },
    { slug: "nilometer-fustat-south", nameEn: "South Cairo: Fustat, Roda, and the Nilometer", nameAr: "جنوب القاهرة: الفسطاط والروضة ومقياس النيل", descriptionEn: "Explore the southern historic areas including Fustat and the Nilometer on Roda Island.", descriptionAr: "استكشف المناطق التاريخية الجنوبية بما فيها الفسطاط ومقياس النيل في جزيرة الروضة.", durationMinutes: 150, distanceMeters: 4000, difficulty: "moderate" as const, stops: [{placeSlug: "mosque-amr-ibn-al-as", order: 1}, {placeSlug: "nilometer-roda", order: 2}], hasStaleInfo: false, status: "published" as const, sortOrder: 16 },
    { slug: "ibn-tulun-gayer-anderson", nameEn: "Ibn Tulun and the Gayer-Anderson Museum", nameAr: "ابن طولون ومتحف غاير أندرسون", descriptionEn: "Combine the Ibn Tulun Mosque with the adjacent Gayer-Anderson Museum of historic Islamic domestic interiors.", descriptionAr: "اجمع بين جامع ابن طولون ومتحف غاير أندرسون المجاور للتصاميم الداخلية الإسلامية التاريخية.", durationMinutes: 150, distanceMeters: 1000, difficulty: "easy" as const, stops: [{placeSlug: "mosque-ibn-tulun", order: 1}], hasStaleInfo: false, status: "published" as const, sortOrder: 17 },
    { slug: "complete-historic-cairo", nameEn: "Complete Historic Cairo: Full-Day Survey", nameAr: "القاهرة التاريخية الكاملة: مسح ليوم كامل", descriptionEn: "A full-day walk covering the major zones of Historic Cairo from Fustat to the Northern Cemetery.", descriptionAr: "جولة ليوم كامل تغطي المناطق الرئيسية للقاهرة التاريخية من الفسطاط إلى القرافة الشمالية.", durationMinutes: 480, distanceMeters: 8000, difficulty: "challenging" as const, stops: [{placeSlug: "mosque-ibn-tulun", order: 1}, {placeSlug: "al-muizz-street", order: 2}, {placeSlug: "al-azhar-mosque", order: 3}, {placeSlug: "cairo-citadel", order: 4}, {placeSlug: "faraj-ibn-barquq-khanqah", order: 5}], hasStaleInfo: false, status: "published" as const, sortOrder: 18 },
  ];

  for (const walk of walksData) {
    await db.insert(walks).ignore().values(walk as any);
  }

  // COMPARISONS
  console.log("  → Seeding comparisons...");
  await db.insert(comparisons).ignore().values([
    { slug: "sultan-hasan-vs-rifai", titleEn: "Sultan Hasan vs. Al-Rifa'i: Medieval vs. Modern", titleAr: "السلطان حسن مقابل الرفاعي: الوسيط مقابل الحديث", descriptionEn: "Compare the 14th-century Mamluk masterpiece with its 19th-century historicist neighbor.", descriptionAr: "قارن بين التحفة المملوكية من القرن الرابع عشر وجارها التاريخاني من القرن التاسع عشر.", explanationEn: "These two monuments face each other across a narrow street, yet are separated by five centuries of architectural history. Sultan Hasan uses hand-cut stone, organic muqarnas, and massive proportions born of medieval craft. Al-Rifa'i uses machine-cut stone and historicist detailing to evoke the same tradition.", explanationAr: "يتواجه هذان المعلمان عبر شارع ضيق رغم فصل خمسة قرون من التاريخ المعماري بينهما.", placeIds: [12, 13], status: "published" as const, sortOrder: 1 },
    { slug: "bab-futuh-vs-bab-nasr", titleEn: "Bab al-Futuh vs. Bab al-Nasr: Two Gates, One Wall", titleAr: "باب الفتوح مقابل باب النصر: بوابتان وسور واحد", descriptionEn: "Compare the two northern Fatimid gates built simultaneously by Badr al-Jamali.", descriptionAr: "قارن بين البوابتين الفاطميتين الشماليتين المبنيتين في آن واحد بيد بدر الجمالي.", explanationEn: "Built at the same time by the same patron, these two gates use different tower forms — rounded at Bab al-Futuh, rectangular at Bab al-Nasr — and different decorative programs.", explanationAr: "بُنيت البوابتان في الوقت ذاته من قبل الراعي نفسه لكنهما تستخدمان أشكال أبراج مختلفة.", placeIds: [6, 7], status: "published" as const, sortOrder: 2 },
    { slug: "ibn-tulun-vs-al-azhar", titleEn: "Ibn Tulun vs. Al-Azhar: Two Founding Mosques", titleAr: "ابن طولون مقابل الأزهر: جامعان مؤسسان", descriptionEn: "Compare the Tulunid and Fatimid founding mosques of Cairo's two early capitals.", descriptionAr: "قارن بين الجامعين المؤسسين الطولوني والفاطمي لعاصمتي القاهرة المبكرتين.", explanationEn: "Both mosques were built as the congregational centers of new capitals, yet they differ radically in scale, material, plan, and decorative approach.", explanationAr: "بُني كلا الجامعين مركزين جامعين لعاصمتين جديدتين لكنهما يختلفان اختلافاً جذرياً في الحجم والمادة والمخطط والنهج الزخرفي.", placeIds: [3, 4], status: "published" as const, sortOrder: 3 },
    { slug: "qalawun-vs-barquq", titleEn: "Qalawun vs. Barquq: Bahri and Burji Mamluk Patronage", titleAr: "قلاوون مقابل برقوق: رعاية المماليك البحرية والبرجية", descriptionEn: "Compare the two great complexes that face each other at Bayn al-Qasrayn.", descriptionAr: "قارن بين المجمعين العظيمين المتقابلين في بين القصرين.", explanationEn: "Separated by a century, these two complexes both served as royal foundations combining mosque, madrasa, and mausoleum.", explanationAr: "يفصل بين هذين المجمعين قرن من الزمن وكلاهما خدم بوصفه تأسيساً ملكياً يجمع مسجداً ومدرسة وضريحاً.", placeIds: [11, 20], status: "published" as const, sortOrder: 4 },
  ] as any[]);

  // DETECTIVE ACTIVITIES
  console.log("  → Seeding detective activities...");
  await db.insert(detectiveActivities).ignore().values([
    { slug: "find-spiral-minaret", titleEn: "Find the Spiral Minaret", titleAr: "ابحث عن المئذنة الحلزونية", activityType: "find_detail" as const, placeId: 3, promptEn: "Which mosque in Cairo has a minaret with an external spiral staircase, unique in Egypt and echoing a famous mosque in Iraq?", promptAr: "أي جامع في القاهرة يضم مئذنة بدرج خارجي حلزوني، فريد في مصر ويستحضر جامعاً مشهوراً في العراق؟", options: ["Mosque of Ibn Tulun", "Al-Azhar Mosque", "Mosque of al-Hakim", "Bab al-Futuh"], correctAnswer: "Mosque of Ibn Tulun", explanationEn: "The Mosque of Ibn Tulun has the only external spiral staircase minaret in Egypt, echoing the famous spiral minaret of the Great Mosque of Samarra in Iraq.", explanationAr: "جامع ابن طولون هو الوحيد في مصر الذي يضم مئذنة بدرج خارجي حلزوني.", difficulty: "beginner" as const, status: "published" as const, sortOrder: 1 },
    { slug: "street-or-qibla-aqmar", titleEn: "Street or Qibla? The Aqmar Puzzle", titleAr: "الشارع أم القبلة؟ لغز الأقمر", activityType: "street_or_qibla" as const, placeId: 9, promptEn: "Al-Aqmar Mosque faces al-Muizz Street, but the prayer hall must face Mecca. How did the builders solve this geometric conflict?", promptAr: "يواجه جامع الأقمر شارع المعز، لكن قاعة الصلاة يجب أن تتجه نحو مكة. كيف حلّ البناؤون هذا التعارض الهندسي؟", options: ["They built two separate prayer halls", "They used an angled interior plan", "They ignored the qibla direction", "They rotated the entire building"], correctAnswer: "They used an angled interior plan", explanationEn: "The builders of al-Aqmar aligned the façade with al-Muizz Street while using an angled interior plan to orient the prayer hall correctly toward Mecca.", explanationAr: "واجه بناؤو الأقمر الواجهة مع شارع المعز مع استخدام مخطط داخلي مائل لتوجيه قاعة الصلاة نحو مكة.", difficulty: "intermediate" as const, status: "published" as const, sortOrder: 2 },
    { slug: "which-century-dome", titleEn: "Which Century? Identify the Dome Style", titleAr: "أي قرن؟ حدّد طراز القبة", activityType: "which_century" as const, promptEn: "Mamluk carved stone domes evolved over two centuries. Which period produced the most elaborate floral and geometric dome patterns?", promptAr: "تطورت القباب الحجرية المملوكية المنحوتة على مدى قرنين. أي حقبة أنتجت أكثر أنماط القباب الزهرية والهندسية تفصيلاً؟", options: ["14th century Bahri Mamluk", "15th century Burji Mamluk", "16th century early Ottoman", "13th century Ayyubid"], correctAnswer: "15th century Burji Mamluk", explanationEn: "The most elaborate carved stone domes, combining geometric and floral patterns, date to the Burji Mamluk period of the 15th century.", explanationAr: "أكثر القباب الحجرية المنحوتة تفصيلاً تعود إلى عصر المماليك البرجية في القرن الخامس عشر.", difficulty: "intermediate" as const, status: "published" as const, sortOrder: 3 },
    { slug: "match-silhouette-gates", titleEn: "Match the Gate Silhouette", titleAr: "طابق صورة ظل البوابة", activityType: "match_silhouette" as const, promptEn: "Three Fatimid gates survive in Cairo. Which gate is uniquely identified by twin minarets rising from its towers?", promptAr: "ثلاث بوابات فاطمية باقية في القاهرة. أي بوابة تتميز بمآذن توأم ترتفع من أبراجها؟", options: ["Bab al-Futuh", "Bab al-Nasr", "Bab Zuweila"], correctAnswer: "Bab Zuweila", explanationEn: "Bab Zuweila is uniquely identified by the twin minarets of the Mosque of al-Mu'ayyad Shaykh rising from its towers.", explanationAr: "يتميز باب زويلة بالمآذن التوأم لجامع المؤيد شيخ التي ترتفع من أبراجه.", difficulty: "beginner" as const, status: "published" as const, sortOrder: 4 },
    { slug: "patron-network-qalawun", titleEn: "The Qalawun Dynasty: Patron Network", titleAr: "أسرة قلاوون: شبكة الرعاة", activityType: "patron_network" as const, placeId: 11, promptEn: "Sultan Qalawun founded a dynasty that built many of Cairo's greatest monuments. Which of these was NOT commissioned by a Qalawun descendant?", promptAr: "أسس السلطان قلاوون أسرة بنت كثيراً من أعظم معالم القاهرة. Which of these was NOT commissioned by a Qalawun descendant?", options: ["Mosque of al-Nasir Muhammad", "Mosque of Sultan Hasan", "Mosque of Ibn Tulun", "Complex of Barquq"], correctAnswer: "Mosque of Ibn Tulun", explanationEn: "The Mosque of Ibn Tulun was built by the Tulunid dynasty in 879 CE, centuries before the Qalawun dynasty. Sultan Hasan was a Qalawun descendant; al-Nasir Muhammad was Qalawun's son; Barquq's complex faces Qalawun's on al-Muizz Street.", explanationAr: "بُني جامع ابن طولون بيد الأسرة الطولونية عام ٨٧٩م، قبل أسرة قلاوون بقرون.", difficulty: "advanced" as const, status: "published" as const, sortOrder: 5 },
    { slug: "material-detective-marble", titleEn: "Material Detective: Identify the Marble Source", titleAr: "محقق المواد: حدّد مصدر الرخام", activityType: "material_detective" as const, promptEn: "Mamluk builders used colored marble extensively in their monuments. Where did much of this marble originally come from?", promptAr: "استخدم بناؤو المماليك الرخام الملوّن على نطاق واسع في معالمهم. من أين جاء معظم هذا الرخام في الأصل؟", options: ["Quarried fresh in Egypt", "Spolia from ancient Egyptian temples", "Imported from Italy", "Spolia from Byzantine churches and Roman buildings"], correctAnswer: "Spolia from Byzantine churches and Roman buildings", explanationEn: "Much of the colored marble in Mamluk monuments was spolia — reused material taken from earlier Byzantine churches, Roman buildings, and Crusader structures.", explanationAr: "معظم الرخام الملوّن في المعالم المملوكية كان من الأسبوليا، أي مواد مُعاد استخدامها من كنائس بيزنطية ومبانٍ رومانية وإنشاءات صليبية.", difficulty: "advanced" as const, status: "published" as const, sortOrder: 6 },
    { slug: "find-muqarnas", titleEn: "Find the Muqarnas", titleAr: "ابحث عن المقرنصات", activityType: "find_detail" as const, promptEn: "Muqarnas are a distinctive feature of Islamic architecture. What are they?", promptAr: "المقرنصات سمة مميزة للعمارة الإسلامية. ما هي؟", options: ["A type of geometric tile pattern", "Stalactite-like three-dimensional decorative vaulting", "A form of Arabic calligraphy carved in stone", "A type of pointed arch"], correctAnswer: "Stalactite-like three-dimensional decorative vaulting", explanationEn: "Muqarnas are three-dimensional decorative vaulting elements that resemble stalactites. They are used to transition between different geometric forms and to fill recessed portals and domes.", explanationAr: "المقرنصات عناصر تقبيب زخرفية ثلاثية الأبعاد تشبه الصواعد الكهفية. تُستخدم للانتقال بين الأشكال الهندسية المختلفة.", difficulty: "beginner" as const, status: "published" as const, sortOrder: 7 },
    { slug: "date-the-minaret", titleEn: "Date the Minaret: Tulunid, Fatimid, or Mamluk?", titleAr: "أرّخ المئذنة: طولونية أم فاطمية أم مملوكية؟", activityType: "which_century" as const, promptEn: "Cairo's minarets evolved significantly over the centuries. Which minaret type typically features a square base, octagonal middle, and cylindrical top?", promptAr: "تطورت مآذن القاهرة تطوراً كبيراً على مر القرون. أي نوع من المآذن يتميز عادةً بقاعدة مربعة وجزء أوسط مثمن وقمة أسطوانية؟", options: ["Tulunid spiral", "Fatimid cylindrical", "Mamluk three-tiered", "Ottoman pencil"], correctAnswer: "Mamluk three-tiered", explanationEn: "The classic Mamluk minaret has three tiers: a square base, an octagonal middle section, and a cylindrical top with a bulbous finial.", explanationAr: "للمئذنة المملوكية الكلاسيكية ثلاثة طوابق: قاعدة مربعة وجزء أوسط مثمن وقمة أسطوانية بتاج بصلي.", difficulty: "intermediate" as const, status: "published" as const, sortOrder: 8 },
    { slug: "sacred-site-protocol", titleEn: "Sacred Site Protocol: What to Do", titleAr: "بروتوكول الموقع المقدس: ماذا تفعل", activityType: "find_detail" as const, promptEn: "When visiting an active mosque in Cairo, which of the following is most important?", promptAr: "عند زيارة مسجد نشط في القاهرة، أي مما يلي هو الأهم؟", options: ["Take as many photos as possible", "Remove shoes before entering the prayer hall and dress modestly", "Visit during prayer times for the best atmosphere", "Touch the decorative elements for a closer look"], correctAnswer: "Remove shoes before entering the prayer hall and dress modestly", explanationEn: "Removing shoes before entering the prayer hall and dressing modestly are the most important protocols when visiting active mosques. Photography inside active prayer halls is often not appropriate.", explanationAr: "خلع الحذاء قبل دخول قاعة الصلاة والتلبس بشكل محتشم هما أهم البروتوكولات عند زيارة المساجد النشطة.", difficulty: "beginner" as const, status: "published" as const, sortOrder: 9 },
    { slug: "identify-period-facade", titleEn: "Identify the Period from the Façade", titleAr: "حدّد الحقبة من الواجهة", activityType: "which_century" as const, promptEn: "A mosque façade features a large central dome, pencil-thin minarets, and extensive tile work with Iznik patterns. Which period does this suggest?", promptAr: "تتميز واجهة مسجد بقبة مركزية كبيرة ومآذن قلمية رفيعة وأعمال بلاط واسعة بأنماط إزنيق. أي حقبة يشير إليه هذا؟", options: ["Fatimid", "Bahri Mamluk", "Early Ottoman", "Muhammad Ali dynasty"], correctAnswer: "Early Ottoman", explanationEn: "Large central domes, pencil minarets, and Iznik tile work are characteristic of Early Ottoman architecture in Cairo, introduced after the Ottoman conquest of 1517.", explanationAr: "القباب المركزية الكبيرة والمآذن القلمية وأعمال بلاط إزنيق سمات مميزة للعمارة العثمانية المبكرة في القاهرة.", difficulty: "intermediate" as const, status: "published" as const, sortOrder: 10 },
  ] as any[]);

  // STORIES
  console.log("  → Seeding stories...");
  await db.insert(stories).ignore().values([
    { slug: "the-spiral-staircase-secret", titleEn: "The Secret of the Spiral Staircase", titleAr: "سر الدرج الحلزوني", descriptionEn: "How did the builders of Ibn Tulun's mosque create a minaret unlike any other in Egypt?", descriptionAr: "كيف أنشأ بناؤو جامع ابن طولون مئذنة لا مثيل لها في مصر؟", placeId: 3, storyType: "architectural" as const, chaptersJson: JSON.stringify([
      { order: 1, titleEn: "A New Capital Needs a New Mosque", titleAr: "عاصمة جديدة تحتاج جامعاً جديداً", bodyEn: "When Ahmad Ibn Tulun established his new capital al-Qata'i north of Fustat in 868 CE, he needed a congregational mosque that would express his independence from the Abbasid caliphate in Baghdad.", bodyAr: "حين أسس أحمد بن طولون عاصمته الجديدة القطائع شمال الفسطاط عام ٨٦٨م، احتاج إلى جامع يعبّر عن استقلاليته عن الخلافة العباسية في بغداد." },
      { order: 2, titleEn: "The Samarra Connection", titleAr: "الصلة بسامراء", bodyEn: "Ibn Tulun had grown up in Samarra, the Abbasid capital in Iraq, where the Great Mosque had a famous spiral minaret. When he built his own mosque, he echoed that form — but made it his own by placing the spiral stair on the outside.", bodyAr: "نشأ ابن طولون في سامراء، العاصمة العباسية في العراق، حيث كان للجامع الكبير مئذنة حلزونية مشهورة. حين بنى جامعه، استحضر ذلك الشكل لكنه جعله خاصاً به بوضع الدرج الحلزوني في الخارج." },
      { order: 3, titleEn: "The Only One in Egypt", titleAr: "الوحيد في مصر", bodyEn: "The external spiral staircase minaret of Ibn Tulun remains the only one of its kind in Egypt. It was damaged and rebuilt in the 13th century by Sultan Lajin, but the spiral form was preserved.", bodyAr: "تبقى مئذنة جامع ابن طولون ذات الدرج الحلزوني الخارجي الوحيدة من نوعها في مصر. تضررت وأُعيد بناؤها في القرن الثالث عشر بيد السلطان لاجين، لكن الشكل الحلزوني حُفظ." },
    ]), status: "published" as const, sortOrder: 1 },
    { slug: "the-hospital-that-healed-all", titleEn: "The Hospital That Healed All", titleAr: "البيمارستان الذي شفى الجميع", descriptionEn: "The remarkable story of Qalawun's hospital that served patients of all faiths and backgrounds.", descriptionAr: "القصة الرائعة لبيمارستان قلاوون الذي خدم مرضى من جميع الأديان والخلفيات.", placeId: 11, storyType: "social" as const, chaptersJson: JSON.stringify([
      { order: 1, titleEn: "A Sultan's Vow", titleAr: "نذر سلطان", bodyEn: "Sultan Qalawun is said to have vowed to build a hospital after recovering from an illness while staying in Damascus, where he was treated at the famous Nuri hospital.", bodyAr: "يُقال إن السلطان قلاوون نذر أن يبني بيمارستاناً بعد شفائه من مرض أثناء إقامته في دمشق، حيث عولج في البيمارستان النوري الشهير." },
      { order: 2, titleEn: "Open to All", titleAr: "مفتوح للجميع", bodyEn: "The bimaristan of Qalawun was remarkable for its time: it served patients regardless of religion, gender, or social status. It had separate wards for men and women, for different illnesses, and even a section for the mentally ill.", bodyAr: "تميّز بيمارستان قلاوون لعصره: خدم المرضى بصرف النظر عن دينهم أو جنسهم أو وضعهم الاجتماعي. كانت له أجنحة منفصلة للرجال والنساء ولأمراض مختلفة وحتى قسم للمرضى النفسيين." },
      { order: 3, titleEn: "A Living Legacy", titleAr: "إرث حي", bodyEn: "The hospital continued to function for centuries. Today, the site still contains a hospital — the Qalawun Hospital — making it one of the longest continuously operating medical sites in the world.", bodyAr: "استمر البيمارستان في العمل لقرون. يضم الموقع اليوم مستشفى قلاوون، مما يجعله أحد أطول المواقع الطبية استمراراً في العالم." },
    ]), status: "published" as const, sortOrder: 2 },
    { slug: "the-gate-that-witnessed-history", titleEn: "The Gate That Witnessed History", titleAr: "البوابة التي شهدت التاريخ", descriptionEn: "Bab Zuweila has witnessed Cairo's greatest processions and its darkest moments.", descriptionAr: "شهد باب زويلة أعظم مواكب القاهرة وأحلك لحظاتها.", placeId: 8, storyType: "historical" as const, chaptersJson: JSON.stringify([
      { order: 1, titleEn: "The Southern Gate", titleAr: "البوابة الجنوبية", bodyEn: "Built in 1092 CE as the southern gate of Fatimid Cairo, Bab Zuweila controlled the main road leading south from the city.", bodyAr: "بُني باب زويلة عام ١٠٩٢م بوصفه البوابة الجنوبية للقاهرة الفاطمية، يتحكم في الطريق الرئيسي المؤدي جنوباً من المدينة." },
      { order: 2, titleEn: "Processions and Executions", titleAr: "المواكب والإعدامات", bodyEn: "For centuries, Bab Zuweila was the starting point for great Fatimid processions and later the site of public punishments. The last Mamluk sultan, Tumanbay, was hanged here in 1517 after the Ottoman conquest.", bodyAr: "لقرون، كان باب زويلة نقطة انطلاق المواكب الفاطمية الكبرى وموقعاً للعقوبات العامة لاحقاً. شُنق آخر سلاطين المماليك طومان باي هنا عام ١٥١٧م بعد الفتح العثماني." },
      { order: 3, titleEn: "The Minarets Above", titleAr: "المآذن في الأعلى", bodyEn: "In the early 15th century, Sultan al-Mu'ayyad Shaykh built his mosque directly against the gate, placing its twin minarets on top of the gate's towers — creating one of Cairo's most distinctive skyline compositions.", bodyAr: "في مطلع القرن الخامس عشر، بنى السلطان المؤيد شيخ جامعه مباشرةً إلى جانب البوابة، واضعاً مآذنه التوأم فوق أبراج البوابة، مما خلق أحد أكثر تأليفات أفق القاهرة تميزاً." },
    ]), status: "published" as const, sortOrder: 3 },
    { slug: "the-street-of-ten-centuries", titleEn: "The Street of Ten Centuries", titleAr: "شارع عشرة قرون", descriptionEn: "Al-Muizz Street has been the spine of Cairo for over a thousand years.", descriptionAr: "كان شارع المعز عموداً فقرياً للقاهرة لأكثر من ألف عام.", placeId: 18, storyType: "urban" as const, chaptersJson: JSON.stringify([
      { order: 1, titleEn: "The Fatimid Axis", titleAr: "المحور الفاطمي", bodyEn: "When the Fatimid general Jawhar al-Siqilli founded al-Qahira in 969 CE, he laid out a ceremonial axis running north to south between two royal palaces. This became al-Muizz Street.", bodyAr: "حين أسس القائد الفاطمي جوهر الصقلي القاهرة عام ٩٦٩م، رسم محوراً احتفالياً يمتد من الشمال إلى الجنوب بين قصرين ملكيين. أصبح هذا شارع المعز." },
      { order: 2, titleEn: "The Mamluk Transformation", titleAr: "التحول المملوكي", bodyEn: "After the Fatimid palaces were demolished, the Mamluk sultans transformed the street into a showcase of royal patronage. Complex after complex rose along its length, each sultan competing with his predecessors.", bodyAr: "بعد هدم القصور الفاطمية، حوّل سلاطين المماليك الشارع إلى عرض للرعاية الملكية. تتالت المجمعات على امتداده، كل سلطان ينافس أسلافه." },
      { order: 3, titleEn: "A Living Street Today", titleAr: "شارع حي اليوم", bodyEn: "Today, al-Muizz Street is pedestrianized and bustling with daily life, commerce, and worship. It contains more major medieval Islamic monuments per meter than almost any other street in the world.", bodyAr: "اليوم، شارع المعز مخصص للمشاة ومفعم بالحياة اليومية والتجارة والعبادة. يضم أكثر المعالم الإسلامية الوسيطة الكبرى لكل متر من أي شارع آخر في العالم تقريباً." },
    ]), status: "published" as const, sortOrder: 4 },
    { slug: "reading-the-dome", titleEn: "Reading the Dome: A Visual Language", titleAr: "قراءة القبة: لغة بصرية", descriptionEn: "How to read the carved stone domes of the Mamluk period as a visual language of power and faith.", descriptionAr: "كيفية قراءة القباب الحجرية المنحوتة في العصر المملوكي بوصفها لغة بصرية للسلطة والإيمان.", storyType: "architectural" as const, chaptersJson: JSON.stringify([
      { order: 1, titleEn: "Why Domes?", titleAr: "لماذا القباب؟", bodyEn: "The dome is the most visible element of an Islamic mausoleum. It marks the presence of a tomb from a distance and signals the importance of the person buried beneath.", bodyAr: "القبة هي العنصر الأكثر ظهوراً في الضريح الإسلامي. تُشير إلى وجود قبر من بعيد وتدل على أهمية الشخص المدفون تحتها." },
      { order: 2, titleEn: "The Evolution of Carving", titleAr: "تطور النحت", bodyEn: "Early Mamluk domes were plain or had simple ribbing. By the 15th century, Burji Mamluk craftsmen had developed elaborate geometric and floral patterns that covered the entire dome surface.", bodyAr: "كانت القباب المملوكية المبكرة سادة أو ذات تضليع بسيط. بحلول القرن الخامس عشر، طور حرفيو المماليك البرجية أنماطاً هندسية وزهرية متقنة تغطي سطح القبة بأكمله." },
      { order: 3, titleEn: "Reading the Pattern", titleAr: "قراءة النمط", bodyEn: "The patterns on Mamluk domes are not random decoration. Geometric patterns reflect mathematical and cosmological thinking; floral patterns reference paradise gardens. Together they create a visual theology.", bodyAr: "الأنماط على القباب المملوكية ليست زخرفة عشوائية. تعكس الأنماط الهندسية التفكير الرياضي والكوني؛ وتستحضر الأنماط الزهرية حدائق الجنة. معاً تخلق لاهوتاً بصرياً." },
    ]), status: "published" as const, sortOrder: 5 },
  ] as any[]);

  console.log("✅ Seeding complete!");
  await connection.end();
}

seed().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
