#!/usr/bin/env python3
"""
Minarets of Cairo - Research Generator
Generates a structured JSON + Markdown research package for 123 historic places.
Uses only Python standard library. No network access or API keys required.
"""

import json
import csv
import argparse
import os
from pathlib import Path
from datetime import datetime

def get_raw_data():
    """
    Complete researched dataset for 123 places.
    Format: (slug, status, nameEn, nameAr, placeType, district, period, patron, date)
    """
    return [
        ("al-aqmar-mosque", "PUBLISHED_MEDIA", "Al-Aqmar Mosque", "مسجد الأقمر", "mosque", "al-Gamaliya", "Fatimid", "Al-Ma'mun al-Bata'ihi", "1125"),
        ("al-azhar-mosque", "PUBLISHED_MEDIA", "Al-Azhar Mosque", "الجامع الأزهر", "mosque", "al-Hussein", "Fatimid", "Jawhar al-Siqilli", "970"),
        ("al-azhar-park", "PUBLISHED_MEDIA", "Al-Azhar Park", "حديقة الأزهر", "park", "al-Darb al-Ahmar", "Modern", "Aga Khan Trust for Culture", "2005"),
        ("al-hussein-mosque", "PUBLISHED_MEDIA", "Al-Hussein Mosque and District", "مسجد الحسين ومنطقته", "mosque", "al-Hussein", "Fatimid/Ayyubid", "Various", "1154"),
        ("al-muizz-street", "PUBLISHED_MEDIA", "Al-Muizz Street", "شارع المعز لدين الله", "street", "al-Gamaliya", "Fatimid to Ottoman", "Various", "969"),
        ("al-rifai-mosque", "PUBLISHED_MEDIA", "Al-Rifa'i Mosque", "مسجد الرفاعي", "mosque", "al-Khalifa", "Khedival", "Hoshiyar Qadin", "1911"),
        ("bab-al-futuh", "PUBLISHED_MEDIA", "Bab al-Futuh", "باب الفتوح", "gate", "al-Gamaliya", "Fatimid", "Badr al-Jamali", "1087"),
        ("bab-al-nasr", "PUBLISHED_MEDIA", "Bab al-Nasr", "باب النصر", "gate", "al-Gamaliya", "Fatimid", "Badr al-Jamali", "1087"),
        ("bab-zuweila", "PUBLISHED_MEDIA", "Bab Zuweila", "باب زويلة", "gate", "al-Darb al-Ahmar", "Fatimid", "Badr al-Jamali", "1092"),
        ("barquq-complex", "PUBLISHED_MEDIA", "Madrasa and Khanqah of Sultan Barquq", "مدرسة وخانقاه السلطان برقوق", "complex", "al-Gamaliya", "Mamluk", "Sultan Barquq", "1384"),
        ("bayn-al-qasrayn", "PUBLISHED_MEDIA", "Bayn al-Qasrayn", "بين القصرين", "square", "al-Gamaliya", "Fatimid", "Various", "969"),
        ("bayt-al-suhaymi", "PUBLISHED_MEDIA", "Bayt al-Suhaymi", "بيت السحيمي", "house", "al-Gamaliya", "Ottoman", "Abd al-Wahab al-Tablawi", "1648"),
        ("cairo-citadel", "PUBLISHED_MEDIA", "Cairo Citadel", "قلعة صلاح الدين", "fortress", "al-Khalifa", "Ayyubid", "Saladin", "1176"),
        ("citadel-of-cairo", "PUBLISHED_MEDIA", "Cairo Citadel", "قلعة صلاح الدين", "fortress", "al-Khalifa", "Ayyubid", "Saladin", "1176"),
        ("complex-barquq-muizz", "PUBLISHED_MEDIA", "Khanqah and Mosque of Faraj ibn Barquq", "خانقاه ومسجد فرج بن برقوق", "complex", "al-Gamaliya", "Mamluk", "Faraj ibn Barquq", "1399"),
        ("complex-qalawun", "PUBLISHED_MEDIA", "Qalawun Complex", "مجمع قلاوون", "complex", "al-Gamaliya", "Mamluk", "Sultan Qalawun", "1284"),
        ("complex-sultan-hasan", "PUBLISHED_MEDIA", "Mosque and Madrasa of Sultan Hasan", "مسجد ومدرسة السلطان حسن", "complex", "al-Khalifa", "Mamluk", "Sultan Hasan", "1356"),
        ("faraj-ibn-barquq-khanqah", "PUBLISHED_MEDIA", "Khanqah and Mosque of Faraj ibn Barquq", "خانقاه ومسجد فرج بن برقوق", "complex", "Northern Cemetery", "Mamluk", "Faraj ibn Barquq", "1399"),
        ("khan-al-khalili", "PUBLISHED_MEDIA", "Khan al-Khalili", "خان الخليلي", "market", "al-Gamaliya", "Mamluk/Ottoman", "Various", "1382"),
        ("mosque-al-aqmar", "PUBLISHED_MEDIA", "Al-Aqmar Mosque", "مسجد الأقمر", "mosque", "al-Gamaliya", "Fatimid", "Al-Ma'mun al-Bata'ihi", "1125"),
        ("mosque-al-azhar", "PUBLISHED_MEDIA", "Al-Azhar Mosque", "الجامع الأزهر", "mosque", "al-Hussein", "Fatimid", "Jawhar al-Siqilli", "970"),
        ("mosque-al-ghuri", "PUBLISHED_MEDIA", "Mosque and Mausoleum of al-Ghuri", "مسجد وضريح الغوري", "mosque", "al-Ghuriya", "Mamluk", "Sultan al-Ghuri", "1503"),
        ("mosque-al-hakim", "PUBLISHED_MEDIA", "Mosque of al-Hakim bi-Amr Allah", "مسجد الحاكم بأمر الله", "mosque", "al-Gamaliya", "Fatimid", "Al-Hakim bi-Amr Allah", "1012"),
        ("mosque-al-hussein", "PUBLISHED_MEDIA", "Al-Hussein Mosque and District", "مسجد الحسين ومنطقته", "mosque", "al-Hussein", "Fatimid", "Various", "1154"),
        ("mosque-al-muayyad", "PUBLISHED_MEDIA", "Mosque of al-Mu'ayyad", "مسجد المؤيد شيخ", "mosque", "al-Darb al-Ahmar", "Mamluk", "Sultan al-Mu'ayyad Shaykh", "1415"),
        ("mosque-al-nasir-muhammad-citadel", "PUBLISHED_MEDIA", "Mosque of al-Nasir Muhammad at the Citadel", "مسجد الناصر محمد بالقلعة", "mosque", "al-Khalifa", "Mamluk", "Al-Nasir Muhammad", "1318"),
        ("mosque-al-rifai", "PUBLISHED_MEDIA", "Al-Rifa'i Mosque", "مسجد الرفاعي", "mosque", "al-Khalifa", "Khedival", "Hoshiyar Qadin", "1911"),
        ("mosque-al-salih-ayyub", "PUBLISHED_MEDIA", "Madrasa and Mausoleum of al-Salih Ayyub", "مدرسة وضريح الصالح أيوب", "mosque", "al-Gamaliya", "Ayyubid", "Al-Salih Ayyub", "1242"),
        ("mosque-al-salih-talai", "PUBLISHED_MEDIA", "Mosque of al-Salih Tala'i", "مسجد الصالح طلائع", "mosque", "al-Darb al-Ahmar", "Fatimid", "Tala'i ibn Ruzzik", "1160"),
        ("mosque-amr-ibn-al-as", "PUBLISHED_MEDIA", "Mosque of Amr ibn al-As", "مسجد عمرو بن العاص", "mosque", "Fustat", "Early Islamic", "Amr ibn al-As", "641"),
        ("mosque-ibn-tulun", "PUBLISHED_MEDIA", "Mosque of Ahmad Ibn Tulun", "مسجد أحمد بن طولون", "mosque", "Sayyida Zaynab", "Tulunid", "Ahmad ibn Tulun", "879"),
        ("mosque-muhammad-ali-citadel", "PUBLISHED_MEDIA", "Mosque of Muhammad Ali", "مسجد محمد علي", "mosque", "al-Khalifa", "Ottoman", "Muhammad Ali Pasha", "1830"),
        ("muhammad-ali-mosque", "PUBLISHED_MEDIA", "Mosque of Muhammad Ali", "مسجد محمد علي", "mosque", "al-Khalifa", "Ottoman", "Muhammad Ali Pasha", "1830"),
        ("museum-islamic-art", "PUBLISHED_MEDIA", "Museum of Islamic Art", "متحف الفن الإسلامي", "museum", "al-Khalifa", "Modern", "Egyptian Government", "1903"),
        ("museum-of-islamic-art", "PUBLISHED_MEDIA", "Museum of Islamic Art", "متحف الفن الإسلامي", "museum", "al-Khalifa", "Modern", "Egyptian Government", "1903"),
        ("nilometer-roda", "PUBLISHED_MEDIA", "Nilometer on Roda Island", "مقياس النيل بالروضة", "monument", "Roda Island", "Abbasid", "Al-Mutawakkil", "861"),
        ("qalawun-complex", "PUBLISHED_MEDIA", "Qalawun Complex", "مجمع قلاوون", "complex", "al-Gamaliya", "Mamluk", "Sultan Qalawun", "1284"),
        ("sabil-abd-al-rahman-katkhuda", "PUBLISHED_MEDIA", "Sabil-Kuttab of Abd al-Rahman Katkhuda", "سبيل وكتاب عبد الرحمن كتخدا", "sabil", "al-Gamaliya", "Ottoman", "Abd al-Rahman Katkhuda", "1744"),
        ("sabil-kuttab-abd-al-rahman-katkhuda", "PUBLISHED_MEDIA", "Sabil-Kuttab of Abd al-Rahman Katkhuda", "سبيل وكتاب عبد الرحمن كتخدا", "sabil", "al-Gamaliya", "Ottoman", "Abd al-Rahman Katkhuda", "1744"),
        ("sultan-hasan-mosque", "PUBLISHED_MEDIA", "Mosque and Madrasa of Sultan Hasan", "مسجد ومدرسة السلطان حسن", "mosque", "al-Khalifa", "Mamluk", "Sultan Hasan", "1356"),
        ("wakala-al-ghuri", "PUBLISHED_MEDIA", "Wakala of al-Ghuri", "وكالة الغوري", "commercial", "al-Ghuriya", "Mamluk", "Sultan al-Ghuri", "1504"),
        ("aqunsqur-blue-mosque", "PROPOSED_V4", "Aqsunqur Mosque / Blue Mosque", "مسجد أقسنقر / المسجد الأزرق", "mosque", "al-Darb al-Ahmar", "Mamluk/Ottoman", "Shams al-Din Aqsunqur", "1346"),
        ("bayt-al-razzaz", "PROPOSED_V4", "Bayt al-Razzaz", "بيت الرزاز", "house", "al-Darb al-Ahmar", "Mamluk/Ottoman", "Various", "15th C"),
        ("gayer-anderson-museum", "PROPOSED_V4", "Gayer-Anderson Museum", "متحف جاير أندرسون", "museum", "Sayyida Zaynab", "Ottoman", "Various", "1631"),
        ("mausoleum-imam-al-shafii", "PROPOSED_V4", "Mausoleum of Imam al-Shafi'i", "ضريح الإمام الشافعي", "mausoleum", "Southern Cemetery", "Ayyubid", "Saladin", "1211"),
        ("mausoleum-shajarat-al-durr", "PROPOSED_V4", "Mausoleum of Shajarat al-Durr", "ضريح شجرة الدر", "mausoleum", "Sayyida Zaynab", "Mamluk", "Shajarat al-Durr", "1250"),
        ("mosque-sabil-sulayman-agha-al-silahdar", "PROPOSED_V4", "Mosque-Sabil-Kuttab of Sulayman Agha al-Silahdar", "مسجد وسبيل وكتاب سليمان أغا السلحدار", "mosque", "al-Khalifa", "Ottoman", "Sulayman Agha al-Silahdar", "1839"),
        ("sabil-kuttab-nafisa-al-bayda", "PROPOSED_V4", "Sabil-Kuttab of Nafisa al-Bayda", "سبيل وكتاب نفيسة البيضا", "sabil", "al-Darb al-Ahmar", "Ottoman", "Nafisa al-Bayda", "1744"),
        ("sinan-pasha-mosque-bulaq", "PROPOSED_V4", "Sinan Pasha Mosque", "مسجد سنان باشا", "mosque", "Bulaq", "Ottoman", "Sinan Pasha", "1571"),
        ("sulayman-pasha-al-khadim-mosque", "PROPOSED_V4", "Mosque of Sulayman Pasha al-Khadim", "مسجد سليمان باشا الخادم", "mosque", "al-Khalifa", "Ottoman", "Sulayman Pasha al-Khadim", "1528"),
        ("sultan-qaytbay-funerary-complex", "PROPOSED_V4", "Funerary Complex of Sultan Qaytbay", "مجمع السلطان قايتباي الجنائزي", "complex", "Northern Cemetery", "Mamluk", "Sultan Qaytbay", "1472"),
        ("abu-al-ila-mosque-district", "CANDIDATE", "Abu al-Ila Mosque and District", "مسجد أبو العلا ومنطقته", "mosque", "Bulaq", "Mamluk", "Abu al-Ila", "15th C"),
        ("ayyubid-wall-darb-al-ahmar", "CANDIDATE", "Ayyubid Wall in Darb al-Ahmar", "سور الأيوبيين بالدرب الأحمر", "wall", "al-Darb al-Ahmar", "Ayyubid", "Saladin", "1170"),
        ("azbakiyya-urban-history", "CANDIDATE", "Azbakiyya Islamic Urban History", "تاريخ الأزبكية العمراني", "district", "Azbakiyya", "Mamluk/Ottoman", "Various", "15th C"),
        ("bab-al-wazir-street", "CANDIDATE", "Bab al-Wazir Street Ensemble", "مجمع شارع باب الوزير", "street", "al-Darb al-Ahmar", "Mamluk", "Various", "14th C"),
        ("barsbay-northern-cemetery", "CANDIDATE", "Funerary Complex of Barsbay", "مجمع الأشرف برسباي", "complex", "Northern Cemetery", "Mamluk", "Sultan Barsbay", "1432"),
        ("bayt-al-harrawi", "CANDIDATE", "Bayt al-Harrawi", "بيت الهراوي", "house", "al-Darb al-Ahmar", "Ottoman", "Abd al-Rahman al-Harrawi", "1731"),
        ("bayt-al-sinnari", "CANDIDATE", "Bayt al-Sinnari", "بيت السناري", "house", "Sayyida Zaynab", "Ottoman", "Ahmad Katkhuda al-Sinnari", "1740"),
        ("bayt-gamal-al-din-al-dhahabi", "CANDIDATE", "Bayt Gamal al-Din al-Dhahabi", "بيت جمال الدين الذهبي", "house", "al-Darb al-Ahmar", "Ottoman", "Gamal al-Din al-Dhahabi", "1637"),
        ("bayt-sitt-wasila", "CANDIDATE", "Bayt Sitt Wasila", "بيت ست وسيلة", "house", "al-Darb al-Ahmar", "Ottoman", "Sitt Wasila", "1673"),
        ("bayt-zaynab-khatun", "CANDIDATE", "Bayt Zaynab Khatun", "بيت زينب خاتون", "house", "al-Darb al-Ahmar", "Ottoman", "Zaynab Khatun", "1486"),
        ("bulaq-historic-port", "CANDIDATE", "Historic Port District of Bulaq", "ميناء بولاق التاريخي", "district", "Bulaq", "Mamluk", "Various", "14th C"),
        ("burg-al-mahruq", "CANDIDATE", "Burg al-Mahruq", "برج المحروق", "tower", "Fustat", "Fatimid", "Various", "11th C"),
        ("cairo-aqueduct", "CANDIDATE", "Cairo Aqueduct", "قنال القاهرة المائي", "infrastructure", "Fustat", "Mamluk", "Al-Nasir Muhammad", "1312"),
        ("citadel-northern-enclosure", "CANDIDATE", "Northern Enclosure of the Citadel", "الحرم الشمالي للقلعة", "fortress", "al-Khalifa", "Ayyubid", "Saladin", "1176"),
        ("citadel-well-yusuf", "CANDIDATE", "Well of Yusuf at the Citadel", "بئر يوسف بالقلعة", "infrastructure", "al-Khalifa", "Ayyubid", "Saladin", "1185"),
        ("excavated-houses-fustat", "CANDIDATE", "Excavated Houses of Fustat", "منازل الفسطاط المكتشفة", "archaeological", "Fustat", "Early Islamic", "Various", "7th C"),
        ("fumm-al-khalig", "CANDIDATE", "Historic Mouth of the Khalij", "فم الخليج التاريخي", "district", "Fustat", "Fatimid", "Various", "10th C"),
        ("fustat-archaeological-area", "CANDIDATE", "Fustat Archaeological Area", "منطقة الفسطاط الأثرية", "archaeological", "Fustat", "Early Islamic", "Various", "641"),
        ("fustat-pottery-kilns", "CANDIDATE", "Fustat Pottery and Kilns", "أفران فخار الفسطاط", "archaeological", "Fustat", "Fatimid", "Various", "10th C"),
        ("gawhara-palace", "CANDIDATE", "Al-Gawhara Palace", "قصر الجوهرة", "palace", "al-Khalifa", "Ottoman", "Muhammad Ali Pasha", "1814"),
        ("hammam-bishtak", "CANDIDATE", "Hammam of Bashtak", "حمام بشتاك", "bath", "al-Gamaliya", "Mamluk", "Bashtak", "14th C"),
        ("hammam-sukkariyya", "CANDIDATE", "Historic Hammam in al-Sukkariyya", "حمام السكرية التاريخي", "bath", "al-Gamaliya", "Mamluk", "Various", "14th C"),
        ("historic-crafts-darb-al-ahmar", "CANDIDATE", "Historic Crafts of Darb al-Ahmar", "حرف الدرب الأحمر التاريخية", "district", "al-Darb al-Ahmar", "Mamluk", "Various", "14th C"),
        ("imam-shafii-cemetery-landscape", "CANDIDATE", "Imam al-Shafi'i Cemetery Landscape", "مقبرة الإمام الشافعي", "cemetery", "Southern Cemetery", "Ayyubid", "Various", "1211"),
        ("khanqah-shaykhu", "CANDIDATE", "Khanqah of Amir Shaykhu", "خانقاه الأمير شيخو", "complex", "Sayyida Zaynab", "Mamluk", "Amir Shaykhu", "1349"),
        ("khayrbak-complex", "CANDIDATE", "Complex of Amir Khayrbak", "مجمع الأمير خير بك", "complex", "al-Darb al-Ahmar", "Mamluk/Ottoman", "Amir Khayrbak", "1502"),
        ("madrasa-al-kamil", "CANDIDATE", "Madrasa of al-Kamil Muhammad", "مدرسة الكامل محمد", "mosque", "al-Gamaliya", "Ayyubid", "Al-Kamil Muhammad", "1238"),
        ("madrasa-al-zahir-baybars-remains", "CANDIDATE", "Remains of Madrasa of al-Zahir Baybars", "بقايا مدرسة الظاهر بيبرس", "archaeological", "al-Gamaliya", "Mamluk", "Al-Zahir Baybars", "1264"),
        ("madrasa-sarghatmish", "CANDIDATE", "Madrasa of Sarghatmish", "مدرسة صرغطميش", "mosque", "Sayyida Zaynab", "Mamluk", "Amir Sarghatmish", "1356"),
        ("madrasa-taghri-bardi", "CANDIDATE", "Mosque-Madrasa of Taghri Bardi", "مسجد ومدرسة تغري بردي", "mosque", "Sayyida Zaynab", "Mamluk", "Taghri Bardi", "1440"),
        ("madrasa-umm-al-sultan-shaban", "CANDIDATE", "Madrasa of Umm al-Sultan Sha'ban", "مدرسة أم السلطان شعبان", "mosque", "al-Darb al-Ahmar", "Mamluk", "Umm al-Sultan Sha'ban", "1368"),
        ("manasterly-palace", "CANDIDATE", "Manasterly Palace", "قصر المانسترلي", "palace", "Roda Island", "Ottoman", "Hassan Fouad Pasha al-Manasterly", "1851"),
        ("manzil-ali-labib", "CANDIDATE", "Manzil Ali Labib", "منزل علي لبيب", "house", "al-Darb al-Ahmar", "Ottoman", "Ali Labib", "18th C"),
        ("maristan-al-muayyadi", "CANDIDATE", "Bimaristan of al-Mu'ayyad", "بيمارستان المؤيدي", "hospital", "al-Darb al-Ahmar", "Mamluk", "Sultan al-Mu'ayyad", "1418"),
        ("mashhad-al-juyushi", "CANDIDATE", "Mashhad al-Juyushi", "مشهد الجيوشي", "shrine", "Mokattam", "Fatimid", "Badr al-Jamali", "1085"),
        ("mausoleum-amir-qurqumas", "CANDIDATE", "Mausoleum of Amir Qurqumas", "ضريح الأمير قرقماس", "mausoleum", "Northern Cemetery", "Mamluk", "Amir Qurqumas", "1506"),
        ("mausoleum-janibak-al-ashrafi", "CANDIDATE", "Mausoleum of Janibak al-Ashrafi", "ضريح جنبك الأشرفي", "mausoleum", "Northern Cemetery", "Mamluk", "Janibak al-Ashrafi", "1427"),
        ("mausoleum-qansuh-abu-said", "CANDIDATE", "Mausoleum of Qansuh Abu Sa'id", "ضريح قانصوه أبو سعيد", "mausoleum", "Northern Cemetery", "Mamluk", "Qansuh Abu Sa'id", "1499"),
        ("mausoleum-sayyida-atika", "CANDIDATE", "Mausoleum of Sayyida Atika", "ضريح السيدة عتيقة", "mausoleum", "Sayyida Zaynab", "Mamluk", "Sayyida Atika", "15th C"),
        ("mausoleum-sayyida-ruqayya", "CANDIDATE", "Mausoleum of Sayyida Ruqayya", "ضريح السيدة رقية", "mausoleum", "Southern Cemetery", "Fatimid", "Sayyida Ruqayya", "1133"),
        ("mausoleum-sayyida-sukayna", "CANDIDATE", "Mausoleum of Sayyida Sukayna", "ضريح السيدة سكينة", "mausoleum", "Southern Cemetery", "Fatimid", "Sayyida Sukayna", "12th C"),
        ("mausoleum-tarabay-al-sharifi", "CANDIDATE", "Mausoleum of Tarabay al-Sharifi", "ضريح طراباي الشريفي", "mausoleum", "Southern Cemetery", "Mamluk", "Tarabay al-Sharifi", "1503"),
        ("mausoleum-yunus-al-dawadar", "CANDIDATE", "Mausoleum of Yunus al-Dawadar", "ضريح يونس الدوادار", "mausoleum", "Northern Cemetery", "Mamluk", "Yunus al-Dawadar", "1382"),
